import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createTodoStore} from './todoStore.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-todo-'));return [d,join(d,'state','todos.json')];}
test('missing file is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createTodoStore(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add persists canonical todo and restart survives',async()=>{const [,p]=await fresh();const s=createTodoStore(p);const t=await s.add({id:'a',text:'  first  '});assert.deepEqual(t,{id:'a',text:'first',done:false});assert.deepEqual(JSON.parse(await readFile(p,'utf8')),[{id:'a',text:'first',done:false}]);assert.deepEqual(await createTodoStore(p).get('a'),t);});
test('duplicate id rejects without changing disk',async()=>{const [,p]=await fresh();const s=createTodoStore(p);await s.add({id:'a',text:'x'});await assert.rejects(s.add({id:'a',text:'y'}),/DUPLICATE_ID/);assert.equal((await s.list()).length,1);});
test('update and toggle persist while preserving order',async()=>{const [,p]=await fresh();const s=createTodoStore(p);await s.add({id:'a',text:'x'});await s.add({id:'b',text:'y'});await s.update('a',{text:'xx'});await s.toggle('b');assert.deepEqual(await s.list(),[{id:'a',text:'xx',done:false},{id:'b',text:'y',done:true}]);});
test('remove returns removed todo and missing ids fail closed',async()=>{const [,p]=await fresh();const s=createTodoStore(p);await s.add({id:'a',text:'x'});assert.deepEqual(await s.remove('a'),{id:'a',text:'x',done:false});assert.deepEqual(await s.list(),[]);for(const fn of [()=>s.update('x',{done:true}),()=>s.toggle('x'),()=>s.remove('x')]) await assert.rejects(fn(),/NOT_FOUND/);});
test('validation rejects empty ids/text and unknown patch keys',async()=>{const [,p]=await fresh();const s=createTodoStore(p);await assert.rejects(s.add({id:'',text:'x'}),/INVALID_TODO/);await assert.rejects(s.add({id:'a',text:'   '}),/INVALID_TODO/);await s.add({id:'a',text:'x'});await assert.rejects(s.update('a',{wat:1}),/INVALID_PATCH/);});
test('corrupt or invalid persisted records fail closed and are preserved',async()=>{for(const body of ['{bad','{}','[{"id":"a","text":"","done":false}]','[{"id":"a","text":"x","done":false},{"id":"a","text":"y","done":false}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createTodoStore(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.add({id:'z',text:'z'}),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('returned records are clones and API is frozen',async()=>{const [,p]=await fresh();const s=createTodoStore(p);await s.add({id:'a',text:'x'});const a=await s.get('a');a.text='mutated';assert.equal((await s.get('a')).text,'x');assert.equal(Object.isFrozen(s),true);});
