export const DIAGNOSTIC_PACKS=Object.freeze({
  quick:Object.freeze({label:'Penta Quick Check',description:'Core five-seat readiness, daily Prometheus and Frugal continuity.',tests:['runtime/os/pentarchy.test.mjs','runtime/os/prometheus_daily.test.mjs','runtime/os/prometheus_daily_loop.test.mjs','runtime/os/frugal_reserve.test.mjs']}),
  care:Object.freeze({label:'Care & Recovery',description:'Rhea care, Kronos life, Sclerotium and durable Work recovery.',tests:['runtime/os/rhea.test.mjs','runtime/os/kronos.test.mjs','runtime/os/sclerotium.test.mjs','runtime/os/panda_gap_closure.test.mjs']}),
  intelligence:Object.freeze({label:'Knowledge & Intelligence',description:'Prometheus, Mnemosyne, capability truth, local search and closed quarry.',tests:['runtime/os/prometheus.test.mjs','runtime/os/prometheus_daily.test.mjs','runtime/os/mnemosyne.test.mjs','runtime/os/mnemosyne_quality.test.mjs','runtime/os/context_metabolism.test.mjs','runtime/os/capability_registry.test.mjs','runtime/os/intelligence_foundation.test.mjs','runtime/os/local_semantic_search.test.mjs','runtime/os/skill_contract.test.mjs','runtime/os/great_library_seed.test.mjs','runtime/os/final_quarry_census.test.mjs','runtime/os/panda_backend_harvest.test.mjs']}),
  library:Object.freeze({label:'Great Library Check',description:'Closed quarry, Patterns, Blocks, Blueprints and reuse pressure remain evidence-bound and inert.',tests:['runtime/os/great_library_seed.test.mjs','runtime/os/great_library_potential.test.mjs','runtime/os/great_library_priority.test.mjs','runtime/os/final_quarry_census.test.mjs','runtime/os/skill_contract.test.mjs','runtime/os/panda_backend_harvest.test.mjs']}),
  execution:Object.freeze({label:'Build & Execution',description:'Talos runtime, Work, recovery, sandbox, Hephaestus and Switchyard contracts.',tests:['runtime/talos-kernel/loop.test.ts','runtime/os/work_record.test.mjs','runtime/os/panda_gap_closure.test.mjs','runtime/os/mission_sandbox.test.mjs','runtime/os/switchyard.test.mjs','runtime/os/frugal_reserve.test.mjs']}),
  communications:Object.freeze({label:'Comms & Credentials',description:'Hermes, Keymaster and scoped credential broker fail-closed seams.',tests:['runtime/os/hermes.test.mjs','runtime/os/keymaster.test.mjs','runtime/os/keymaster_vault.test.mjs','runtime/os/credential_broker.test.mjs','runtime/os/credential_usage_ledger.test.mjs']}),
  blood:Object.freeze({label:'Prometheus Blood Loop',description:'Kronos beat, discovery, capability truth, credential custody and free-capacity health.',tests:['runtime/os/kronos_prometheus_beat.test.mjs','runtime/os/prometheus_daily.test.mjs','runtime/os/prometheus_daily_loop.test.mjs','runtime/os/prometheus_news_search.test.mjs','runtime/os/prometheus_arsenal.test.mjs','runtime/os/capability_registry.test.mjs','runtime/os/keymaster_vault.test.mjs','runtime/os/credential_broker.test.mjs','runtime/os/credential_usage_ledger.test.mjs','runtime/os/provider_probe.test.mjs','runtime/os/frugal_reserve.test.mjs','runtime/os/free_capacity.test.mjs']}),
  deep:Object.freeze({label:'OTHRYS Deep Check',description:'Every native OS resident test plus Talos kernel.',glob:'runtime/os/*.test.mjs',extra:['runtime/talos-kernel/loop.test.ts']})
});
export function diagnosticCatalog(){return Object.freeze(Object.entries(DIAGNOSTIC_PACKS).map(([id,p])=>Object.freeze({id,label:p.label,description:p.description,settingsButtonReady:true,mutates:false,authorityGranted:false})));}
