import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createLocalKv} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-'));return [d,join(d,'nested','state.json')];}
test('missing state is empty and read-only calls do not write',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);assert.deepEqual(await kv.list(),{});assert.equal(await kv.get('x'),undefined);await assert.rejects(access(p));});
test('set persists the new value and survives a fresh instance',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);await kv.set('a',{n:1});assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{a:{n:1}});assert.deepEqual(await createLocalKv(p).get('a'),{n:1});});
test('multiple mutations preserve prior state',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);await kv.set('a',1);await kv.set('b',2);assert.deepEqual(await kv.list(),{a:1,b:2});await kv.delete('a');assert.deepEqual(await createLocalKv(p).list(),{b:2});});
test('list sorts keys and clear persists empty state',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);await kv.set('z',1);await kv.set('a',2);assert.deepEqual(Object.keys(await kv.list()),['a','z']);await kv.clear();assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{});});
test('corrupt state fails closed and is never overwritten',async()=>{const [d,p]=await fresh();await import('node:fs/promises').then(f=>f.mkdir(join(d,'nested'),{recursive:true}));await writeFile(p,'{bad','utf8');const kv=createLocalKv(p);await assert.rejects(kv.list(),/STATE_CORRUPT/);await assert.rejects(kv.set('x',1),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),'{bad');});
test('arrays and scalar JSON are corrupt state',async()=>{for(const body of ['[]','null','42']){const [d,p]=await fresh();await import('node:fs/promises').then(f=>f.mkdir(join(d,'nested'),{recursive:true}));await writeFile(p,body);await assert.rejects(createLocalKv(p).list(),/STATE_CORRUPT/);}});
test('invalid keys and non-JSON values are rejected',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);await assert.rejects(kv.get(''),TypeError);for(const v of [undefined,()=>{},Symbol('x'),1n]) await assert.rejects(kv.set('x',v),TypeError);});
test('cyclic values are rejected without changing disk',async()=>{const [,p]=await fresh();const kv=createLocalKv(p);await kv.set('ok',1);const x={};x.self=x;await assert.rejects(kv.set('bad',x),TypeError);assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{ok:1});});
test('API is frozen',async()=>{const [,p]=await fresh();assert.equal(Object.isFrozen(createLocalKv(p)),true);});

