import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createBookmarkStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-bookmarks-'));return [d,join(d,'state','bookmarks.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add canonical bookmark and restart',async()=>{const [,p]=await fresh();let s=await createBookmarkStore(p);const b=await s.add({id:'b1',url:' https://EXAMPLE.com/a ',title:'  A ',tags:[' x ','y']});assert.deepEqual(b,{id:'b1',url:'https://example.com/a',title:'A',tags:['x','y']});s=await createBookmarkStore(p);assert.deepEqual(await s.get('b1'),b);});
test('duplicate and invalid bookmark reject',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);await s.add({id:'b1',url:'https://a.test',title:'',tags:[]});await assert.rejects(s.add({id:'b1',url:'https://b.test',title:'',tags:[]}),/DUPLICATE_ID/);for(const b of [{id:'',url:'https://a.test',title:'',tags:[]},{id:'x',url:'ftp://a.test',title:'',tags:[]},{id:'x',url:'bad',title:'',tags:[]},{id:'x',url:'https://a.test',title:'',tags:['']},{id:'x',url:'https://a.test',title:'',tags:[],extra:1}]) await assert.rejects(s.add(b),/INVALID_BOOKMARK/);});
test('update canonicalizes and preserves order',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);await s.add({id:'a',url:'https://a.test',title:'A',tags:[]});await s.add({id:'b',url:'https://b.test',title:'B',tags:[]});await s.update('a',{url:' HTTP://EXAMPLE.COM/x ',title:' x ',tags:[' z ']});assert.deepEqual(await s.list(),[{id:'a',url:'http://example.com/x',title:'x',tags:['z']},{id:'b',url:'https://b.test/',title:'B',tags:[]}]);});
test('remove returns removed and missing mutations reject',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);await s.add({id:'a',url:'https://a.test',title:'',tags:[]});assert.deepEqual(await s.remove('a'),{id:'a',url:'https://a.test/',title:'',tags:[]});for(const f of [()=>s.update('x',{title:'x'}),()=>s.remove('x')])await assert.rejects(f(),/NOT_FOUND/);});
test('bad patch rejects',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);await s.add({id:'a',url:'https://a.test',title:'',tags:[]});for(const pch of [{},{id:'x'},{url:'ftp://a.test'},{tags:['']}])await assert.rejects(s.update('a',pch),/INVALID_PATCH/);});
test('corrupt state is preserved',async()=>{for(const body of ['{bad','{}','[{"id":"a","url":"https://a.test/","title":"","tags":[]},{"id":"a","url":"https://b.test/","title":"","tags":[]}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);await assert.rejects(createBookmarkStore(p).list(),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('deep clones and frozen API',async()=>{const [,p]=await fresh();const s=await createBookmarkStore(p);await s.add({id:'a',url:'https://a.test',title:'',tags:['x']});const b=await s.get('a');b.tags.push('y');assert.deepEqual((await s.get('a')).tags,['x']);assert.equal(Object.isFrozen(s),true);});
