import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createJournal} from './journal.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-journal-'));return [d,join(d,'state','journal.jsonl')];}
const e=(id,type='NOTE',at='2026-08-30T12:00:00.000Z',data={x:1})=>({id,type,at,data});
test('missing journal is empty and reads do not write',async()=>{const [,p]=await fresh();const j=createJournal(p);assert.deepEqual(await j.list(),[]);assert.equal(await j.count(),0);assert.equal(await j.at(0),undefined);await assert.rejects(access(p));});
test('append persists canonical JSONL and survives restart',async()=>{const [,p]=await fresh();const j=createJournal(p);const a=e('a');assert.deepEqual(await j.append(a),a);const raw=await readFile(p,'utf8');assert.equal(raw,JSON.stringify(a)+'\n');assert.deepEqual(await createJournal(p).list(),[a]);});
test('append preserves prior bytes and order',async()=>{const [,p]=await fresh();const j=createJournal(p);await j.append(e('a'));const before=await readFile(p,'utf8');await j.append(e('b','TASK','2026-08-30T12:01:00.000Z',[1,2]));const after=await readFile(p,'utf8');assert.ok(after.startsWith(before));assert.equal((await j.at(1)).id,'b');assert.equal(await j.count(),2);});test('duplicate id rejects without mutation',async()=>{const [,p]=await fresh();const j=createJournal(p);await j.append(e('a'));const before=await readFile(p,'utf8');await assert.rejects(j.append(e('a')),/DUPLICATE_ID/);assert.equal(await readFile(p,'utf8'),before);});
test('invalid event and unsafe/non-json data reject before write',async()=>{const [,p]=await fresh();const j=createJournal(p);for(const bad of [{id:'',type:'X',at:'2026-08-30T12:00:00.000Z',data:{}},{id:'a',type:' ',at:'2026-08-30T12:00:00.000Z',data:{}},{id:'a',type:'X',at:'2026-08-30',data:{}},{id:'a',type:'X',at:'2026-08-30T12:00:00.000Z',data:{n:Infinity}}]) await assert.rejects(j.append(bad));const cyc={};cyc.self=cyc;await assert.rejects(j.append(e('a','X','2026-08-30T12:00:00.000Z',cyc)));await assert.rejects(access(p));});
test('corrupt journal fails closed and remains byte-identical',async()=>{for(const raw of ['{bad\n',JSON.stringify(e('a'))+'\n'+JSON.stringify(e('a'))+'\n',JSON.stringify({id:'a',type:'X',at:'bad',data:{}})+'\n']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const j=createJournal(p);await assert.rejects(j.list(),/STATE_CORRUPT/);await assert.rejects(j.append(e('z')),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('returned values are deep clones and API frozen',async()=>{const [,p]=await fresh();const j=createJournal(p);await j.append(e('a','X','2026-08-30T12:00:00.000Z',{arr:[1]}));const x=await j.at(0);x.data.arr.push(2);assert.deepEqual((await j.at(0)).data.arr,[1]);assert.equal(Object.isFrozen(j),true);});