import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {materializeBuildPackage} from './build_package.ts';
const selection={selected:{id:'qwen3-builder',label:'Qwen3 8B · Legion',class:'LOCAL ENGINEERING',status:'PRIMARY',available:true,evidence:'V2-002C'},reason:'PRIMARY_LOCAL_AVAILABLE'};const sha=(v:any)=>createHash('sha256').update(JSON.stringify(v),'utf8').digest('hex');
function fx(){const d=mkdtempSync(join(tmpdir(),'build-package-')),m=join(d,'missions'),out=join(d,'packages');mkdirSync(m);const id='V2-009A';writeFileSync(join(m,`${id}.json`),JSON.stringify({mission_id:id,objective:'Add missing widget',status:'CANONICAL_UNACTIVATED',authorityGranted:false,executionStarted:false})+'\n');const route={schema:'othrys.os.build-route.v1',missionId:id,authorityGranted:false,executionStarted:false,status:'ROUTE_PROPOSED',reason:'PRIMARY_LOCAL_AVAILABLE',selected:{id:'qwen3-builder',label:'Qwen3 8B · Legion',class:'LOCAL ENGINEERING',status:'PRIMARY',evidence:'V2-002C'}},routeDigest=sha(route),receivedAt='2026-08-28T15:30:00.000Z',intent={action:'MISSION_BUILD_REQUEST',missionId:id,builderId:'qwen3-builder',routeDigest,receivedAt},intentDigest=sha(intent),requestId=`DECK-BUILD-${intentDigest.slice(0,24)}`,inbox=join(d,'inbox.jsonl'),ledger=join(d,'ledger.jsonl');writeFileSync(inbox,JSON.stringify({...intent,schema:'othrys.deck.intent.v1',authorityGranted:false,status:'PENDING_TRUST_CANAL'})+'\n');writeFileSync(ledger,JSON.stringify({missionId:requestId,state:'ADMITTED'})+'\n');return {d,id,out,inbox,ledger};}

test('fresh admitted build request materializes non-executing package',()=>{const f=fx();try{const r=materializeBuildPackage(f.d,f.id,selection,f.inbox,f.ledger,f.out);assert.equal(r.created,true);assert.equal(r.package.builderId,'qwen3-builder');assert.equal(r.package.status,'READY_NOT_EXECUTING');assert.equal(r.package.executionStarted,false);assert.equal(r.package.authorityGranted,false);}finally{rmSync(f.d,{recursive:true,force:true});}});
test('stale request is rejected when mission now has NO_CHANGE evidence',()=>{const f=fx();try{writeFileSync(join(f.d,'missions',`${f.id}.preflight.json`),JSON.stringify({schema:'othrys.os.mission-preflight.v1',missionId:f.id,verdict:'NO_CHANGE_JUSTIFIED',objectiveSatisfied:true,mutationRequired:false,builderRequired:false,authorityGranted:false,executionStarted:false})+'\n');assert.throws(()=>materializeBuildPackage(f.d,f.id,selection,f.inbox,f.ledger,f.out),/BUILD_REQUEST_STALE/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('route mismatch cannot reuse admitted build request',()=>{const f=fx();try{const other={selected:{...selection.selected,id:'other-builder'},reason:'PRIMARY_LOCAL_AVAILABLE'};assert.throws(()=>materializeBuildPackage(f.d,f.id,other,f.inbox,f.ledger,f.out),/BUILD_REQUEST_MISSING/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('package replay is idempotent',()=>{const f=fx();try{const a=materializeBuildPackage(f.d,f.id,selection,f.inbox,f.ledger,f.out),b=materializeBuildPackage(f.d,f.id,selection,f.inbox,f.ledger,f.out);assert.equal(a.created,true);assert.equal(b.created,false);assert.deepEqual(a.package,b.package);}finally{rmSync(f.d,{recursive:true,force:true});}});
