import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {materializeChangeCandidate} from './change_candidate.ts';
const acceptance={schema:'othrys.os.worker-acceptance.v1',missionId:'V2-009A',jobId:'JOB-0123456789abcdef01234567',builderId:'qwen3-builder',changedFiles:['scratch/a.txt'],status:'ACCEPTED_VERIFIED',accepted:true,authorityGranted:false,executionStarted:true};
function fx(){const d=mkdtempSync(join(tmpdir(),'change-candidate-')),p=join(d,'patch.json'),out=join(d,'out');writeFileSync(p,JSON.stringify({schema:'othrys.os.worker-patch-evidence.v1',missionId:'V2-009A',jobId:'JOB-0123456789abcdef01234567',builderId:'qwen3-builder',baseSha:'a'.repeat(40),workspaceClass:'DISPOSABLE_LEGION_WORKTREE',changedFiles:['scratch/a.txt'],diff:'diff --git a/scratch/a.txt b/scratch/a.txt\n+ok\n'})+'\n');return {d,p,out};}

test('accepted worker result becomes non-applied verified change candidate',()=>{const f=fx();try{const r=materializeChangeCandidate(acceptance,f.p,f.out);assert.equal(r.created,true);assert.equal(r.candidate.status,'VERIFIED_CHANGE_CANDIDATE');assert.equal(r.candidate.applyEligible,false);assert.equal(r.candidate.applied,false);assert.match(r.candidate.patchDigest,/^[0-9a-f]{64}$/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('candidate replay is idempotent',()=>{const f=fx();try{const a=materializeChangeCandidate(acceptance,f.p,f.out),b=materializeChangeCandidate(acceptance,f.p,f.out);assert.equal(a.created,true);assert.equal(b.created,false);assert.equal(readFileSync(a.path,'utf8'),readFileSync(b.path,'utf8'));}finally{rmSync(f.d,{recursive:true,force:true});}});

test('identity and scope mismatch fail closed',()=>{const f=fx();try{assert.throws(()=>materializeChangeCandidate({...acceptance,jobId:'JOB-deadbeefdeadbeefdeadbeef'},f.p,f.out),/PATCH_IDENTITY_MISMATCH/);assert.throws(()=>materializeChangeCandidate({...acceptance,changedFiles:['other.txt']},f.p,f.out),/PATCH_SCOPE_MISMATCH/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('invalid base sha fails closed',()=>{const f=fx();try{const p=JSON.parse(readFileSync(f.p,'utf8'));p.baseSha='bad';writeFileSync(f.p,JSON.stringify(p)+'\n');assert.throws(()=>materializeChangeCandidate(acceptance,f.p,f.out),/PATCH_EVIDENCE_INVALID/);}finally{rmSync(f.d,{recursive:true,force:true});}});
