import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';import {executeVerifiedChange} from './change_executor.ts';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
function git(w:string,...a:string[]){return execFileSync('git',['-C',w,...a],{encoding:'utf8'}).trim();}
function fx(){const d=mkdtempSync(join(tmpdir(),'change-exec-')),w=join(d,'repo');mkdirSync(w);git(w,'init','-q');git(w,'config','user.email','test@example.com');git(w,'config','user.name','Test');writeFileSync(join(w,'README.md'),'base\n');git(w,'add','README.md');git(w,'commit','-m','base');const head=git(w,'rev-parse','HEAD'),mission='V2-009A',diff='diff --git a/scratch/a.txt b/scratch/a.txt\nnew file mode 100644\nindex 0000000..587be6b\n--- /dev/null\n+++ b/scratch/a.txt\n@@ -0,0 +1 @@\n+proof\n',pd=sha(diff),cid=`CHANGE-${pd.slice(0,24)}`,permit=join(d,'permit.json'),candidate=join(d,'candidate.json'),patch=join(d,'patch.json');writeFileSync(candidate,JSON.stringify({schema:'othrys.os.change-candidate.v1',candidateId:cid,missionId:mission,baseSha:head,patchDigest:pd,status:'VERIFIED_CHANGE_CANDIDATE',applied:false})+'\n');writeFileSync(patch,JSON.stringify({schema:'othrys.os.worker-patch-evidence.v1',missionId:mission,diff})+'\n');writeFileSync(permit,JSON.stringify({schema:'othrys.os.change-apply-permit.v1',permitId:'APPLY-PERMIT-0123456789abcdef01234567',candidateId:cid,missionId:mission,patchDigest:pd,targetSha:head,changedFiles:['scratch/a.txt'],oneShot:true,consumed:false,status:'APPLY_READY_NOT_STARTED',authorityGranted:true,applied:false},null,2)+'\n');return {d,w,head,permit,candidate,patch};}

test('one-shot executor applies exact patch without commit and consumes permit',()=>{const f=fx();try{const r=executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:10:00Z');assert.equal(r.status,'APPLIED_NOT_COMMITTED');assert.equal(readFileSync(join(f.w,'scratch','a.txt'),'utf8'),'proof\n');assert.equal(git(f.w,'rev-parse','HEAD'),f.head);assert.match(git(f.w,'status','--short','--untracked-files=all'),/scratch\/a.txt/);const p=JSON.parse(readFileSync(f.permit,'utf8'));assert.equal(p.consumed,true);assert.equal(p.applied,true);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('stale HEAD rejects before apply',()=>{const f=fx();try{writeFileSync(join(f.w,'other.txt'),'x\n');git(f.w,'add','other.txt');git(f.w,'commit','-m','advance');assert.throws(()=>executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:10:00Z'),/TARGET_STALE/);assert.equal(JSON.parse(readFileSync(f.permit,'utf8')).consumed,false);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('dirty target rejects before apply',()=>{const f=fx();try{writeFileSync(join(f.w,'dirty.txt'),'x\n');assert.throws(()=>executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:10:00Z'),/TARGET_DIRTY/);assert.equal(JSON.parse(readFileSync(f.permit,'utf8')).consumed,false);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('consumed permit cannot replay',()=>{const f=fx();try{executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:10:00Z');assert.throws(()=>executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:11:00Z'),/PERMIT_STATE_INVALID/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('patch digest mismatch rejects before apply',()=>{const f=fx();try{const p=JSON.parse(readFileSync(f.patch,'utf8'));p.diff=p.diff.replace('+proof','+wrong');writeFileSync(f.patch,JSON.stringify(p)+'\n');assert.throws(()=>executeVerifiedChange(f.w,f.permit,f.candidate,f.patch,'2026-08-28T18:10:00Z'),/PATCH_PERMIT_MISMATCH/);assert.equal(git(f.w,'status','--porcelain','--untracked-files=all'),'');}finally{rmSync(f.d,{recursive:true,force:true});}});
