import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {materializeChangeApplyPermit} from './change_apply_permit.ts';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
function fx(opts:any={}){const d=mkdtempSync(join(tmpdir(),'apply-permit-')),m=join(d,'missions'),cc=join(m,'change-candidates'),out=join(m,'apply-permits');mkdirSync(cc,{recursive:true});const target='a'.repeat(40),mission='V2-009A',diff='diff --git a/scratch/a.txt b/scratch/a.txt\nnew file mode 100644\n--- /dev/null\n+++ b/scratch/a.txt\n@@ -0,0 +1 @@\n+x\n',pd=sha(diff),cid=`CHANGE-${pd.slice(0,24)}`;writeFileSync(join(cc,`${cid}.json`),JSON.stringify({schema:'othrys.os.change-candidate.v1',candidateId:cid,missionId:mission,baseSha:opts.baseSha??target,changedFiles:['scratch/a.txt'],patchDigest:pd,status:'VERIFIED_CHANGE_CANDIDATE',authorityGranted:false,applied:false})+'\n');writeFileSync(join(m,`${mission}.patch.json`),JSON.stringify({schema:'othrys.os.worker-patch-evidence.v1',missionId:mission,diff})+'\n');const receivedAt='2026-08-28T18:10:00.000Z',req={action:'MISSION_CHANGE_APPLY_REQUEST',candidateId:cid,missionId:mission,patchDigest:pd,targetSha:target,receivedAt,authorityGranted:false,status:'PENDING_TRUST_CANAL'},rid=`DECK-APPLY-${sha(JSON.stringify({action:req.action,candidateId:cid,missionId:mission,patchDigest:pd,targetSha:target,receivedAt})).slice(0,24)}`,inbox=join(d,'inbox.jsonl'),ledger=join(d,'ledger.jsonl');writeFileSync(inbox,JSON.stringify(req)+'\n');writeFileSync(ledger,opts.admitted===false?'':JSON.stringify({missionId:rid,state:'ADMITTED'})+'\n');return {d,target,cid,inbox,ledger,out};}

test('admitted exact-base request materializes one-shot apply permit without apply',()=>{const f=fx();try{const r=materializeChangeApplyPermit(f.d,f.cid,f.target,f.inbox,f.ledger,f.out);assert.equal(r.permit.status,'APPLY_READY_NOT_STARTED');assert.equal(r.permit.oneShot,true);assert.equal(r.permit.authorityGranted,true);assert.equal(r.permit.applied,false);assert.deepEqual(r.permit.changedFiles,['scratch/a.txt']);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('stale target is rejected before permit creation',()=>{const f=fx({baseSha:'b'.repeat(40)});try{assert.throws(()=>materializeChangeApplyPermit(f.d,f.cid,f.target,f.inbox,f.ledger,f.out),/TARGET_STALE/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('missing Trust Canal admission is rejected',()=>{const f=fx({admitted:false});try{assert.throws(()=>materializeChangeApplyPermit(f.d,f.cid,f.target,f.inbox,f.ledger,f.out),/APPLY_REQUEST_NOT_ADMITTED/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('permit replay is idempotent',()=>{const f=fx();try{const a=materializeChangeApplyPermit(f.d,f.cid,f.target,f.inbox,f.ledger,f.out),b=materializeChangeApplyPermit(f.d,f.cid,f.target,f.inbox,f.ledger,f.out);assert.equal(a.created,true);assert.equal(b.created,false);assert.deepEqual(a.permit,b.permit);}finally{rmSync(f.d,{recursive:true,force:true});}});
