import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {materializeExecutionLease} from './execution_lease.ts';
const sj=(v:unknown)=>createHash('sha256').update(JSON.stringify(v),'utf8').digest('hex');
function fx(admitted=true){const d=mkdtempSync(join(tmpdir(),'lease-')),out=join(d,'leases'),pkgPath=join(d,'pkg.json'),inbox=join(d,'inbox.jsonl'),ledger=join(d,'ledger.jsonl');const pkg={schema:'othrys.os.build-package.v1',missionId:'V2-009A',builderId:'qwen3-builder',buildRequestId:'DECK-BUILD-0123456789abcdef01234567',status:'READY_NOT_EXECUTING',authorityGranted:false,executionStarted:false};const raw=JSON.stringify(pkg,null,2)+'\n';writeFileSync(pkgPath,raw);const pd=createHash('sha256').update(raw).digest('hex'),receivedAt='2026-08-28T16:00:00.000Z',auth={action:'MISSION_EXECUTION_AUTH_REQUEST',missionId:pkg.missionId,buildRequestId:pkg.buildRequestId,builderId:pkg.builderId,packageDigest:pd,receivedAt,authorityGranted:false,status:'PENDING_TRUST_CANAL'},id=`DECK-EXEC-${sj({action:auth.action,missionId:auth.missionId,buildRequestId:auth.buildRequestId,builderId:auth.builderId,packageDigest:auth.packageDigest,receivedAt}).slice(0,24)}`;writeFileSync(inbox,JSON.stringify(auth)+'\n');writeFileSync(ledger,admitted?JSON.stringify({missionId:id,state:'ADMITTED'})+'\n':'');return {d,out,pkgPath,inbox,ledger};}

test('admitted auth creates short-lived non-started lease',()=>{const f=fx();try{const r=materializeExecutionLease(f.pkgPath,f.inbox,f.ledger,f.out,'2026-08-28T16:05:00.000Z');assert.equal(r.created,true);assert.equal(r.lease.status,'LEASE_READY_NOT_STARTED');assert.equal(r.lease.launchEligible,true);assert.equal(r.lease.authorityGranted,false);assert.equal(r.lease.executionStarted,false);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('missing admission fails closed',()=>{const f=fx(false);try{assert.throws(()=>materializeExecutionLease(f.pkgPath,f.inbox,f.ledger,f.out,'2026-08-28T16:05:00.000Z'),/EXECUTION_AUTH_NOT_ADMITTED/);}finally{rmSync(f.d,{recursive:true,force:true});}});
test('expired authorization fails closed',()=>{const f=fx();try{assert.throws(()=>materializeExecutionLease(f.pkgPath,f.inbox,f.ledger,f.out,'2026-08-28T16:11:00.001Z'),/EXECUTION_AUTH_EXPIRED/);}finally{rmSync(f.d,{recursive:true,force:true});}});
test('lease replay is idempotent',()=>{const f=fx();try{const a=materializeExecutionLease(f.pkgPath,f.inbox,f.ledger,f.out,'2026-08-28T16:05:00.000Z'),b=materializeExecutionLease(f.pkgPath,f.inbox,f.ledger,f.out,'2026-08-28T16:06:00.000Z');assert.equal(a.created,true);assert.equal(b.created,false);assert.deepEqual(a.lease,b.lease);assert.ok(readFileSync(a.path,'utf8').includes('LEASE_READY_NOT_STARTED'));}finally{rmSync(f.d,{recursive:true,force:true});}});
