import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {materializeLaunchPermit} from './launch_permit.ts';
const sj=(v:unknown)=>createHash('sha256').update(JSON.stringify(v),'utf8').digest('hex');
function fx(admitted=true){const d=mkdtempSync(join(tmpdir(),'permit-')),leasePath=join(d,'lease.json'),inbox=join(d,'inbox.jsonl'),ledger=join(d,'ledger.jsonl'),out=join(d,'permits');const lease={schema:'othrys.os.execution-lease.v1',leaseId:'LEASE-0123456789abcdef01234567',missionId:'V2-009A',builderId:'qwen3-builder',issuedAt:'2026-08-28T16:00:00.000Z',expiresAt:'2026-08-28T16:10:00.000Z',status:'LEASE_READY_NOT_STARTED',launchEligible:true,authorityGranted:false,executionStarted:false};const raw=JSON.stringify(lease,null,2)+'\n';writeFileSync(leasePath,raw);const ld=createHash('sha256').update(raw).digest('hex'),receivedAt='2026-08-28T16:05:00.000Z',launch={action:'MISSION_WORKER_LAUNCH_REQUEST',missionId:lease.missionId,leaseId:lease.leaseId,builderId:lease.builderId,leaseDigest:ld,receivedAt,authorityGranted:false,status:'PENDING_TRUST_CANAL'},id=`DECK-LAUNCH-${sj({action:launch.action,missionId:launch.missionId,leaseId:launch.leaseId,builderId:launch.builderId,leaseDigest:launch.leaseDigest,receivedAt}).slice(0,24)}`;writeFileSync(inbox,JSON.stringify(launch)+'\n');writeFileSync(ledger,admitted?JSON.stringify({missionId:id,state:'ADMITTED'})+'\n':'');return {d,leasePath,inbox,ledger,out};}

test('admitted launch creates two-minute one-shot permit',()=>{const f=fx();try{const r=materializeLaunchPermit(f.leasePath,f.inbox,f.ledger,f.out,'2026-08-28T16:06:00.000Z');assert.equal(r.permit.status,'PERMIT_READY_NOT_STARTED');assert.equal(r.permit.oneShot,true);assert.equal(r.permit.consumed,false);assert.equal(r.permit.executionStarted,false);assert.equal(r.permit.expiresAt,'2026-08-28T16:07:00.000Z');}finally{rmSync(f.d,{recursive:true,force:true});}});

test('missing launch admission fails closed',()=>{const f=fx(false);try{assert.throws(()=>materializeLaunchPermit(f.leasePath,f.inbox,f.ledger,f.out,'2026-08-28T16:06:00.000Z'),/LAUNCH_REQUEST_NOT_ADMITTED/);}finally{rmSync(f.d,{recursive:true,force:true});}});
test('expired launch request fails closed',()=>{const f=fx();try{assert.throws(()=>materializeLaunchPermit(f.leasePath,f.inbox,f.ledger,f.out,'2026-08-28T16:07:00.001Z'),/LAUNCH_REQUEST_EXPIRED/);}finally{rmSync(f.d,{recursive:true,force:true});}});
test('permit replay is idempotent',()=>{const f=fx();try{const a=materializeLaunchPermit(f.leasePath,f.inbox,f.ledger,f.out,'2026-08-28T16:06:00.000Z'),b=materializeLaunchPermit(f.leasePath,f.inbox,f.ledger,f.out,'2026-08-28T16:06:30.000Z');assert.equal(a.created,true);assert.equal(b.created,false);assert.deepEqual(a.permit,b.permit);assert.ok(readFileSync(a.path,'utf8').includes('PERMIT_READY_NOT_STARTED'));}finally{rmSync(f.d,{recursive:true,force:true});}});
