import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {closeNoChangeMission} from './no_change_closeout.ts';
const sha=(s:string)=>createHash('sha256').update(s,'utf8').digest('hex');
function fixture(admitted=true){const d=mkdtempSync(join(tmpdir(),'nochange-close-')),missions=join(d,'missions');mkdirSync(missions);const id='V2-008D';writeFileSync(join(missions,`${id}.json`),JSON.stringify({mission_id:id,objective:'already satisfied',status:'CANONICAL_UNACTIVATED',authorityGranted:false,executionStarted:false})+'\n');const p=JSON.stringify({schema:'othrys.os.mission-preflight.v1',missionId:id,verdict:'NO_CHANGE_JUSTIFIED',objectiveSatisfied:true,mutationRequired:false,builderRequired:false,authorityGranted:false,executionStarted:false},null,2)+'\n';writeFileSync(join(missions,`${id}.preflight.json`),p);const digest=sha(p),receivedAt='2026-08-28T14:46:30.920Z',intent={action:'MISSION_NO_CHANGE_CLOSE_REQUEST',missionId:id,preflightDigest:digest,receivedAt,authorityGranted:false,status:'PENDING_TRUST_CANAL'},intentDigest=sha(JSON.stringify({action:intent.action,missionId:id,preflightDigest:digest,receivedAt})),requestId=`DECK-NOCHANGE-${intentDigest.slice(0,24)}`,inbox=join(d,'inbox.jsonl'),ledger=join(d,'ledger.jsonl');writeFileSync(inbox,JSON.stringify(intent)+'\n');writeFileSync(ledger,admitted?JSON.stringify({missionId:requestId,state:'ADMITTED'})+'\n':'');return {d,id,inbox,ledger};}

test('admitted no-change request writes PASS result without execution',()=>{const f=fixture();try{const r=closeNoChangeMission(f.d,f.id,f.inbox,f.ledger);assert.equal(r.created,true);assert.equal(r.result.verdict,'PASS');assert.equal(r.result.closeout,'NO_CHANGE_JUSTIFIED');assert.equal(r.result.executionStarted,false);assert.equal(r.result.authorityGranted,false);assert.equal(r.result.mutations,0);assert.equal(r.result.builderInvoked,false);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('missing admission fails closed and writes no result',()=>{const f=fixture(false);try{assert.throws(()=>closeNoChangeMission(f.d,f.id,f.inbox,f.ledger),/CLOSE_REQUEST_NOT_ADMITTED/);assert.throws(()=>readFileSync(join(f.d,'missions',`${f.id}.result.json`),'utf8'));}finally{rmSync(f.d,{recursive:true,force:true});}});

test('closeout replay is idempotent',()=>{const f=fixture();try{const a=closeNoChangeMission(f.d,f.id,f.inbox,f.ledger),b=closeNoChangeMission(f.d,f.id,f.inbox,f.ledger);assert.equal(a.created,true);assert.equal(b.created,false);assert.deepEqual(a.result,b.result);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('changed preflight after request fails closed',()=>{const f=fixture();try{const path=join(f.d,'missions',`${f.id}.preflight.json`),p=JSON.parse(readFileSync(path,'utf8'));p.evidence=['changed'];writeFileSync(path,JSON.stringify(p,null,2)+'\n');assert.throws(()=>closeNoChangeMission(f.d,f.id,f.inbox,f.ledger),/CLOSE_REQUEST_MISSING/);}finally{rmSync(f.d,{recursive:true,force:true});}});
