import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {decideMissionPreflight} from './preflight_decision.ts';
function root(){const d=mkdtempSync(join(tmpdir(),'preflight-decision-'));mkdirSync(join(d,'missions'));return d;}
function mission(d:string,id='V2-009A'){writeFileSync(join(d,'missions',`${id}.json`),JSON.stringify({mission_id:id,objective:'Build missing capability',status:'CANONICAL_UNACTIVATED',authorityGranted:false,executionStarted:false})+'\n');}

test('canonical mission without satisfaction evidence is MISSING_WORK',()=>{const d=root();try{mission(d);const r=decideMissionPreflight(d,'V2-009A');assert.equal(r.class,'MISSING_WORK');assert.equal(r.reason,'NO_SATISFACTION_EVIDENCE');assert.equal(r.authorityGranted,false);assert.equal(r.executionStarted,false);}finally{rmSync(d,{recursive:true,force:true});}});

test('valid durable no-change evidence is NO_CHANGE',()=>{const d=root();try{mission(d);writeFileSync(join(d,'missions','V2-009A.preflight.json'),JSON.stringify({schema:'othrys.os.mission-preflight.v1',missionId:'V2-009A',verdict:'NO_CHANGE_JUSTIFIED',objectiveSatisfied:true,mutationRequired:false,builderRequired:false,authorityGranted:false,executionStarted:false})+'\n');const r=decideMissionPreflight(d,'V2-009A');assert.equal(r.class,'NO_CHANGE');}finally{rmSync(d,{recursive:true,force:true});}});
test('invalid identity and missing envelope are BLOCKED',()=>{const d=root();try{assert.equal(decideMissionPreflight(d,'bad').class,'BLOCKED');assert.equal(decideMissionPreflight(d,'V2-009A').reason,'MISSION_NOT_FOUND');}finally{rmSync(d,{recursive:true,force:true});}});

test('conflicting preflight evidence is BLOCKED not missing work',()=>{const d=root();try{mission(d);writeFileSync(join(d,'missions','V2-009A.preflight.json'),JSON.stringify({schema:'othrys.os.mission-preflight.v1',missionId:'V2-009A',verdict:'NO_CHANGE_JUSTIFIED',objectiveSatisfied:false,mutationRequired:false,builderRequired:false,authorityGranted:false,executionStarted:false})+'\n');const r=decideMissionPreflight(d,'V2-009A');assert.equal(r.class,'BLOCKED');assert.equal(r.reason,'PREFLIGHT_EVIDENCE_CONFLICT');}finally{rmSync(d,{recursive:true,force:true});}});
