import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {acceptWorkerResult} from './worker_acceptance.ts';
function fx(){const d=mkdtempSync(join(tmpdir(),'accept-worker-')),dispatch=join(d,'dispatch.json'),worker=join(d,'worker.json'),verify=join(d,'verify.json');writeFileSync(dispatch,JSON.stringify({schema:'othrys.os.dispatch-ticket.v1',status:'DISPATCH_AUTHORIZED',authorityGranted:true,missionId:'V2-009A',jobId:'JOB-abc',builderId:'qwen3-builder'})+'\n');writeFileSync(worker,JSON.stringify({schema_version:'othrys.worker-result.v0.1',mission_id:'V2-009A',job_id:'JOB-abc',builder_id:'qwen3-builder',ok:true,allowed_paths:['scratch/a.txt'],changed_files:['scratch/a.txt'],out_of_scope_changes:[]})+'\n');writeFileSync(verify,JSON.stringify({schema:'othrys.os.independent-verification.v1',missionId:'V2-009A',verifier:'T590',verdict:'PASS',checks:{exact:true,scope:true}})+'\n');return {d,dispatch,worker,verify};}

test('accepts only bound worker + dispatch + independent PASS',()=>{const f=fx();try{const r=acceptWorkerResult(f.dispatch,f.worker,f.verify);assert.equal(r.status,'ACCEPTED_VERIFIED');assert.equal(r.accepted,true);assert.equal(r.authorityGranted,false);assert.equal(r.executionStarted,true);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('worker success with out-of-scope change is rejected',()=>{const f=fx();try{writeFileSync(f.worker,JSON.stringify({schema_version:'othrys.worker-result.v0.1',mission_id:'V2-009A',job_id:'JOB-abc',builder_id:'qwen3-builder',ok:true,allowed_paths:['scratch/a.txt'],changed_files:['scratch/a.txt','oops.txt'],out_of_scope_changes:['oops.txt']})+'\n');assert.throws(()=>acceptWorkerResult(f.dispatch,f.worker,f.verify),/WORKER_SCOPE_REJECTED/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('mismatched job or mission is rejected',()=>{const f=fx();try{writeFileSync(f.verify,JSON.stringify({schema:'othrys.os.independent-verification.v1',missionId:'V2-009B',verifier:'T590',verdict:'PASS',checks:{exact:true}})+'\n');assert.throws(()=>acceptWorkerResult(f.dispatch,f.worker,f.verify),/VERIFICATION_INVALID/);}finally{rmSync(f.d,{recursive:true,force:true});}});

test('failed independent check rejects even PASS label',()=>{const f=fx();try{writeFileSync(f.verify,JSON.stringify({schema:'othrys.os.independent-verification.v1',missionId:'V2-009A',verifier:'T590',verdict:'PASS',checks:{exact:true,scope:false}})+'\n');assert.throws(()=>acceptWorkerResult(f.dispatch,f.worker,f.verify),/VERIFICATION_CHECK_FAILED/);}finally{rmSync(f.d,{recursive:true,force:true});}});
