import {promises as fs} from 'node:fs'; import {dirname} from 'node:path'; import {randomUUID} from 'node:crypto';
const plain=v=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype; const clone=structuredClone;
function id(v,err){if(typeof v!=='string'||!v.trim()||v!==v.trim())throw Error(err);return v;} function name(v,err){return id(v,err)}
function item(v,err='INVALID_ITEM'){if(!plain(v)||Object.keys(v).some(k=>!['id','text','done'].includes(k))||!Object.hasOwn(v,'id')||!Object.hasOwn(v,'text'))throw Error(err);const o={id:id(v.id,err),text:name(v.text,err),done:v.done??false};if(typeof o.done!=='boolean')throw Error(err);return o;}
function list(v,err='INVALID_LIST'){if(!plain(v)||Object.keys(v).some(k=>!['id','name','items'].includes(k))||!Object.hasOwn(v,'id')||!Object.hasOwn(v,'name'))throw Error(err);const items=v.items??[];if(!Array.isArray(items))throw Error(err);const seen=new Set(), out=items.map(x=>{const i=item(x,err);if(seen.has(i.id))throw Error(err);seen.add(i.id);return i});return {id:id(v.id,err),name:name(v.name,err),items:out};}
function state(v){if(!plain(v)||Object.keys(v).length!==1||!Array.isArray(v.lists))throw Error('STATE_CORRUPT');const seen=new Set(),lists=v.lists.map(x=>{const l=list(x,'STATE_CORRUPT');if(seen.has(l.id))throw Error('STATE_CORRUPT');seen.add(l.id);return l});return {lists};}
async function load(p){try{const raw=await fs.readFile(p,'utf8');let v;try{v=JSON.parse(raw)}catch{throw Error('STATE_CORRUPT')}const s=state(v);if(JSON.stringify(s)!==raw)throw Error('STATE_CORRUPT');return s;}catch(e){if(e.code==='ENOENT')return {lists:[]};throw e;}}
async function save(p,s){await fs.mkdir(dirname(p),{recursive:true});const t=`${p}.${process.pid}.${randomUUID()}.tmp`;try{await fs.writeFile(t,JSON.stringify(s),'utf8');await fs.rename(t,p)}finally{await fs.rm(t,{force:true}).catch(()=>{})}}
export function createMultiListStore(filePath){const api={async snapshot(){return clone(await load(filePath));},async createList(input){if(!plain(input)||Object.keys(input).some(k=>!['id','name'].includes(k)))throw Error('INVALID_LIST');const l=list({...input,items:[]}),s=await load(filePath);if(s.lists.some(x=>x.id===l.id))throw Error('DUPLICATE_ID');s.lists.push(l);await save(filePath,s);return clone(l);},async renameList(listId,newName){id(listId,'INVALID_LIST');const n=name(newName,'INVALID_LIST'),s=await load(filePath),l=s.lists.find(x=>x.id===listId);if(!l)throw Error('NOT_FOUND');l.name=n;await save(filePath,s);return clone(l);},async deleteList(listId){id(listId,'INVALID_LIST');const s=await load(filePath),i=s.lists.findIndex(x=>x.id===listId);if(i<0)throw Error('NOT_FOUND');const [l]=s.lists.splice(i,1);await save(filePath,s);return clone(l);},async addItem(listId,input){id(listId,'INVALID_LIST');const it=item(input),s=await load(filePath),l=s.lists.find(x=>x.id===listId);if(!l)throw Error('NOT_FOUND');if(l.items.some(x=>x.id===it.id))throw Error('DUPLICATE_ID');l.items.push(it);await save(filePath,s);return clone(it);},async updateItem(listId,itemId,patch){id(listId,'INVALID_LIST');id(itemId,'INVALID_ITEM');if(!plain(patch)||!Object.keys(patch).length||Object.keys(patch).some(k=>!['text','done'].includes(k)))throw Error('INVALID_ITEM');if('text'in patch)name(patch.text,'INVALID_ITEM');if('done'in patch&&typeof patch.done!=='boolean')throw Error('INVALID_ITEM');const s=await load(filePath),l=s.lists.find(x=>x.id===listId);if(!l)throw Error('NOT_FOUND');const it=l.items.find(x=>x.id===itemId);if(!it)throw Error('NOT_FOUND');if('text'in patch)it.text=patch.text;if('done'in patch)it.done=patch.done;await save(filePath,s);return clone(it);},async removeItem(listId,itemId){id(listId,'INVALID_LIST');id(itemId,'INVALID_ITEM');const s=await load(filePath),l=s.lists.find(x=>x.id===listId);if(!l)throw Error('NOT_FOUND');const i=l.items.findIndex(x=>x.id===itemId);if(i<0)throw Error('NOT_FOUND');const [it]=l.items.splice(i,1);await save(filePath,s);return clone(it);}};return Object.freeze(api);}
