import { promises as fs } from 'node:fs';
import { dirname } from 'node:path';
import { randomUUID } from 'node:crypto';
const bad = new Set(['__proto__','prototype','constructor']);
const plain = v => v && typeof v === 'object' && !Array.isArray(v) && Object.getPrototypeOf(v) === Object.prototype;
function canon(v){ if(Array.isArray(v)) return v.map(canon); if(plain(v)){const o={}; for(const k of Object.keys(v).sort()){if(bad.has(k)) throw Error('INVALID_STATE'); o[k]=canon(v[k]);} return o;} if(v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v))) return v; throw Error('INVALID_STATE'); }
function validate(rows, corrupt=false){ if(!Array.isArray(rows)) throw Error(corrupt?'STATE_CORRUPT':'INVALID_STATE'); const ids=new Set(); return rows.map(r=>{if(!plain(r)||typeof r.id!=='string'||!r.id.trim()||r.id!==r.id.trim()||ids.has(r.id)) throw Error(corrupt?'STATE_CORRUPT':'INVALID_STATE'); ids.add(r.id); for(const k of ['status','category']) if(k in r && typeof r[k]!=='string') throw Error(corrupt?'STATE_CORRUPT':'INVALID_STATE'); if('amount' in r && (typeof r.amount!=='number'||!Number.isFinite(r.amount))) throw Error(corrupt?'STATE_CORRUPT':'INVALID_STATE'); try{return canon(r)}catch{throw Error(corrupt?'STATE_CORRUPT':'INVALID_STATE')}}); }
async function load(file){try{const raw=await fs.readFile(file,'utf8'); let v; try{v=JSON.parse(raw)}catch{throw Error('STATE_CORRUPT')} const rows=validate(v,true); if(JSON.stringify(rows)!==raw) throw Error('STATE_CORRUPT'); return rows;}catch(e){if(e.code==='ENOENT') return []; throw e;}}
async function save(file,rows){await fs.mkdir(dirname(file),{recursive:true}); const t=`${file}.${process.pid}.${randomUUID()}.tmp`; try{await fs.writeFile(t,JSON.stringify(rows),'utf8'); await fs.rename(t,file)}finally{await fs.rm(t,{force:true}).catch(()=>{})}}
export function createDashboardSummary(filePath){ const api={async replace(rows){const v=validate(rows); await save(filePath,v); return structuredClone(v)},async summary(){const rows=await load(filePath); const byStatus={},byCategory={}; let totalAmount=0; for(const r of rows){const s=r.status??'(none)',c=r.category??'(none)'; byStatus[s]=(byStatus[s]||0)+1; byCategory[c]=(byCategory[c]||0)+1; totalAmount+=r.amount??0;} const sort=o=>Object.fromEntries(Object.keys(o).sort().map(k=>[k,o[k]])); return structuredClone({count:rows.length,byStatus:sort(byStatus),byCategory:sort(byCategory),totalAmount});}}; return Object.freeze(api); }
