import {readFileSync} from 'node:fs';import {join} from 'node:path';
const COST={ZERO:0,LOW:1,PAID:2};
const PASS=new Set(['PASS','PASS_WITH_FENCE','PASS_WITH_THINKING','PASS_FORMAT_VIOLATION']);
export function loadForgeRoster(root=process.cwd()){const r=JSON.parse(readFileSync(join(root,'runtime','hephaestus','data','forge_roster.json'),'utf8'));if(r.schema!=='othrys.hephaestus.forge-roster.v1')throw new Error('FORGE_ROSTER_INVALID');return r;}
export function loadForgeSparkEvidence(root=process.cwd()){const e=JSON.parse(readFileSync(join(root,'runtime','hephaestus','data','forge_spark_evidence.json'),'utf8'));if(e.schema!=='othrys.hephaestus.forge-spark-evidence.v1')throw new Error('FORGE_SPARK_INVALID');return Object.fromEntries([...e.local,...e.remoteFree].map(x=>[x.id,x]));}
function taskFit(b,task){const tags=new Set(b.specialties??[]);let s=0;for(const t of task.tags??[])if(tags.has(t))s+=3;if(task.localPreferred&&b.locality==='LOCAL')s+=1;if(task.fast&&b.specialties?.some(x=>x.includes('fast')||x.includes('tiny')||x.includes('small')))s+=2;if(task.longContext&&b.specialties?.some(x=>x.includes('long-context')||x.includes('repo-scale')))s+=2;return s;}
function sparkScore(ev){if(!ev)return 0;if(ev.status==='PASS')return 3;if(PASS.has(ev.status))return 1;if(ev.status==='TIMEOUT')return -1;return -3;}
export function rankForgeBuilders(roster,task,{mycelium={metabolicMode:'NORMAL',localPressure:0},evidence={},spark={}}={}){if(!roster||roster.schema!=='othrys.hephaestus.forge-roster.v1')throw new Error('FORGE_ROSTER_INVALID');const rows=roster.builders.map(b=>{const ev=evidence[b.id]??{},sp=spark[b.id]??null;const quality=Number.isFinite(ev.firstPassRate)?ev.firstPassRate:0,latency=Number.isFinite(ev.medianLatencyMs)?ev.medianLatencyMs:(sp?.latencyMs??null);const pressurePenalty=b.locality==='LOCAL'?Math.max(0,Number(mycelium.localPressure)||0)*4:0;const latencyBonus=task.fast&&Number.isFinite(latency)?Math.max(-2,2-latency/8000):0;const recovery=Number.isFinite(ev.recoveryRate)?ev.recoveryRate:0,attemptFailure=Number.isFinite(ev.attemptFailureRate)?ev.attemptFailureRate:0;const learnedPenalty=recovery*5+attemptFailure*4;const score=taskFit(b,task)+(b.executionAllowed?1:0)+quality*5+sparkScore(sp)+latencyBonus-pressurePenalty-learnedPenalty-(COST[b.costClass]??9);return Object.freeze({...b,score:Number(score.toFixed(4)),measuredQuality:quality,measuredRecoveryRate:recovery,measuredAttemptFailureRate:attemptFailure,learnedPenalty:Number(learnedPenalty.toFixed(4)),measuredLatencyMs:latency,sparkStatus:sp?.status??'UNTESTED'});});rows.sort((a,b)=>b.score-a.score||a.qualificationPriority-b.qualificationPriority||a.id.localeCompare(b.id));return Object.freeze({schema:'othrys.hephaestus.forge-ranking.v1',task:Object.freeze({...task}),mycelium:Object.freeze({...mycelium}),ranked:Object.freeze(rows),executable:Object.freeze(rows.filter(x=>x.executionAllowed===true)),qualificationQueue:Object.freeze(rows.filter(x=>x.executionAllowed!==true&&x.endpointAvailable===true)),authorityGranted:false,executionStarted:false});}
export function forgeMyceliumEnvelope({workKey,task,ranking}){if(!workKey||!task||!ranking)throw new Error('FORGE_MYCELIUM_INPUT_REQUIRED');return Object.freeze({schema:'othrys.hephaestus.mycelium-workload.v1',workKey,workloadClass:task.workloadClass??'ENGINEERING',resourceIntent:{preferLocal:task.localPreferred!==false,latencyClass:task.fast?'INTERACTIVE':'NORMAL',parallelism:'INDEPENDENT_ONLY'},candidateRoutes:ranking.ranked.map(x=>({routeId:x.id,locality:x.locality,readiness:x.readiness,score:x.score})),myceliumMayPlace:true,myceliumMayGrantAuthority:false,authorityGranted:false,executionStarted:false});}
