import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createStateMigrator} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-mig-'));return [d,join(d,'state','data.json')];}
const cfg={currentVersion:3,migrations:{1:d=>({...d,b:2}),2:d=>({z:3,...d})}};
test('missing state is virtual current and never writes',async()=>{const [,p]=await fresh();const m=createStateMigrator(p,cfg);assert.deepEqual(await m.inspect(),{version:3,data:{}});assert.deepEqual(await m.migrate(),{fromVersion:3,toVersion:3,changed:false,state:{version:3,data:{}}});await assert.rejects(access(p));});
test('stepwise migration is deterministic and atomic final state',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,'{"version":1,"data":{"a":1}}');const m=createStateMigrator(p,cfg);const r=await m.migrate();assert.equal(r.fromVersion,1);assert.equal(r.toVersion,3);assert.equal(r.changed,true);assert.deepEqual(r.state,{version:3,data:{a:1,b:2,z:3}});assert.equal(await readFile(p,'utf8'),'{"data":{"a":1,"b":2,"z":3},"version":3}');});
test('already-current state does not rewrite',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});const body='{"version":3,"data":{"x":1}}';await writeFile(p,body);const m=createStateMigrator(p,cfg);assert.equal((await m.migrate()).changed,false);assert.equal(await readFile(p,'utf8'),body);});
test('future version rejects',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,'{"version":4,"data":{}}');const m=createStateMigrator(p,cfg);await assert.rejects(m.inspect(),/STATE_FUTURE_VERSION/);await assert.rejects(m.migrate(),/STATE_FUTURE_VERSION/);});
test('corrupt envelope rejects and is preserved',async()=>{for(const body of ['{bad','{"version":1,"data":{},"extra":1}','{"version":0,"data":{}}','{"version":1,"data":42}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const m=createStateMigrator(p,cfg);await assert.rejects(m.inspect(),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('missing migration or thrown migration never partially writes',async()=>{for(const migrations of [{1:d=>({...d,b:2})},{1:d=>({...d,b:2}),2:()=>{throw new Error('boom')}}]){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});const body='{"version":1,"data":{"a":1}}';await writeFile(p,body);const m=createStateMigrator(p,{currentVersion:3,migrations});await assert.rejects(m.migrate(),/MIGRATION_FAILED/);assert.equal(await readFile(p,'utf8'),body);}});
test('unsafe or non-json migration output rejects',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});const body='{"version":1,"data":{}}';await writeFile(p,body);for(const f of [()=>({constructor:1}),()=>({x:undefined}),()=>{const x={};x.self=x;return x;}]){await writeFile(p,body);const m=createStateMigrator(p,{currentVersion:2,migrations:{1:f}});await assert.rejects(m.migrate(),/MIGRATION_FAILED/);assert.equal(await readFile(p,'utf8'),body);}});
test('outputs are cloned and API frozen',async()=>{const [,p]=await fresh();const m=createStateMigrator(p,cfg);const x=await m.inspect();x.data.a=1;assert.deepEqual(await m.inspect(),{version:3,data:{}});assert.equal(Object.isFrozen(m),true);});
