import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createSortPageStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-sortpage-'));return [d,join(d,'state','records.json')];}
const recs=[{id:'a',n:2,s:'b',flag:true},{id:'b',n:1,s:'c',flag:false},{id:'c',n:2,s:'a',flag:false},{id:'d',n:null,s:'a',flag:true}];
test('missing page is empty and read-only',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);assert.deepEqual(await s.page(),{items:[],total:0,offset:0,limit:20});await assert.rejects(access(p));});
test('replace persists and empty sort preserves order',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace(recs);assert.deepEqual((await s.page()).items.map(x=>x.id),['a','b','c','d']);assert.equal(JSON.parse(await readFile(p,'utf8')).length,4);});
test('stable numeric and multi-key sorting',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace(recs);assert.deepEqual((await s.page({sort:[{key:'n',direction:'asc'}]})).items.map(x=>x.id),['b','a','c','d']);assert.deepEqual((await s.page({sort:[{key:'n',direction:'asc'},{key:'s',direction:'asc'}]})).items.map(x=>x.id),['b','c','a','d']);});
test('descending puts nullish before defined and boolean ordering is deterministic',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace(recs);assert.deepEqual((await s.page({sort:[{key:'n',direction:'desc'}]})).items.map(x=>x.id),['d','a','c','b']);assert.deepEqual((await s.page({sort:[{key:'flag',direction:'asc'}]})).items.map(x=>x.id),['b','c','a','d']);});test('pagination reports total and slices after sort',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace(recs);const v=await s.page({sort:[{key:'n',direction:'asc'}],offset:1,limit:2});assert.deepEqual(v,{items:[recs[0],recs[2]],total:4,offset:1,limit:2});});
test('mixed scalar types have deterministic rank',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace([{id:'s',x:'1'},{id:'b',x:false},{id:'n',x:9}]);assert.deepEqual((await s.page({sort:[{key:'x',direction:'asc'}]})).items.map(x=>x.id),['n','s','b']);});
test('invalid query and unsupported sort values reject without mutation',async()=>{const [,p]=await fresh();const s=createSortPageStore(p);await s.replace(recs);const before=await readFile(p,'utf8');for(const q of [{offset:-1},{limit:0},{sort:[{key:'',direction:'asc'}]},{sort:[{key:'n',direction:'up'}]},{sort:[{key:'n',direction:'asc'},{key:'n',direction:'desc'}]},{extra:1}])await assert.rejects(s.page(q),/INVALID_QUERY/);assert.equal(await readFile(p,'utf8'),before);await s.replace([{id:'x',obj:{a:1}}]);const before2=await readFile(p,'utf8');await assert.rejects(s.page({sort:[{key:'obj',direction:'asc'}]}),/INVALID_QUERY/);assert.equal(await readFile(p,'utf8'),before2);});
test('corrupt state fails closed; outputs cloned and API frozen',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,'{bad');const s=createSortPageStore(p);await assert.rejects(s.page(),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),'{bad');const [,p2]=await fresh();const s2=createSortPageStore(p2);await s2.replace([{id:'x',a:[1]}]);const v=await s2.page();v.items[0].a.push(2);assert.deepEqual((await s2.page()).items[0].a,[1]);assert.equal(Object.isFrozen(s2),true);});