import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createSearchStore} from './searchStore.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-search-'));return [d,join(d,'state','records.json')];}
const recs=[{id:'b',name:'Beta',kind:'note',score:2,meta:{z:2,a:1}},{id:'a',name:'Alpha beta',kind:'task',score:1,meta:{b:2,a:1}},{id:'c',name:'Gamma',kind:'note',score:1,meta:null}];
test('missing store is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createSearchStore(p);assert.deepEqual(await s.list(),[]);assert.deepEqual(await s.query(),[]);await assert.rejects(access(p));});
test('replace canonicalizes records and restart survives',async()=>{const [,p]=await fresh();const s=createSearchStore(p);const out=await s.replace(recs);assert.deepEqual(out,recs.map(r=>JSON.parse(JSON.stringify(r,Object.keys(r).sort()))).map((_,i)=>out[i]));const raw=JSON.parse(await readFile(p,'utf8'));assert.equal(raw[0].id,'b');assert.deepEqual(Object.keys(raw[0]),['id','kind','meta','name','score']);assert.deepEqual(Object.keys(raw[0].meta),['a','z']);assert.deepEqual(await createSearchStore(p).list(),raw);});
test('text search is case-insensitive and preserves stored order',async()=>{const [,p]=await fresh();const s=createSearchStore(p);await s.replace(recs);assert.deepEqual((await s.query({text:' BETA ',fields:['name']})).map(x=>x.id),['b','a']);});
test('where filter combines with text deterministically',async()=>{const [,p]=await fresh();const s=createSearchStore(p);await s.replace(recs);assert.deepEqual((await s.query({text:'a',fields:['name'],where:{kind:'note'}})).map(x=>x.id),['b','c']);assert.deepEqual((await s.query({where:{score:1}})).map(x=>x.id),['a','c']);});test('invalid query rejects without mutation',async()=>{const [,p]=await fresh();const s=createSearchStore(p);await s.replace(recs);const before=await readFile(p,'utf8');for(const q of [{text:'x'},{text:1,fields:['name']},{where:{x:{a:1}}},{text:'x',fields:['name','name']},{extra:1}]) await assert.rejects(s.query(q),/INVALID_QUERY/);assert.equal(await readFile(p,'utf8'),before);});
test('invalid replacement rejects before write',async()=>{const [,p]=await fresh();const s=createSearchStore(p);for(const bad of [[{id:'',name:'x'}],[{id:'a'},{id:'a'}],[{id:'a',x:Infinity}]])await assert.rejects(s.replace(bad));await assert.rejects(access(p));});
test('corrupt persisted state fails closed and is preserved',async()=>{for(const raw of ['{bad','{}','[{"id":"a"},{"id":"a"}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const s=createSearchStore(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.replace([{id:'z'}]),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('returned records are deep clones and API frozen',async()=>{const [,p]=await fresh();const s=createSearchStore(p);await s.replace(recs);const x=await s.list();x[0].meta.a=99;assert.equal((await s.list())[0].meta.a,1);assert.equal(Object.isFrozen(s),true);});