import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createMultiListStore} from './multiList.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l223-'));return [d,join(d,'state','lists.json')];}
test('missing snapshot empty/no write, exact frozen API',async()=>{const [,p]=await fresh(),s=createMultiListStore(p);assert(Object.isFrozen(s));assert.deepEqual(Object.keys(s).sort(),['addItem','createList','deleteList','removeItem','renameList','snapshot','updateItem']);assert.deepEqual(await s.snapshot(),{lists:[]});await assert.rejects(access(p));});
test('list and item CRUD persist in order and survive restart',async()=>{const [,p]=await fresh(),s=createMultiListStore(p);assert.deepEqual(await s.createList({id:'a',name:'A'}),{id:'a',name:'A',items:[]});await s.createList({id:'b',name:'B'});assert.deepEqual(await s.addItem('a',{id:'i1',text:'one'}),{id:'i1',text:'one',done:false});await s.addItem('a',{id:'i2',text:'two',done:true});assert.deepEqual(await s.updateItem('a','i1',{done:true,text:'ONE'}),{id:'i1',text:'ONE',done:true});assert.deepEqual((await createMultiListStore(p).snapshot()).lists.map(x=>x.id),['a','b']);});
test('rename/delete/remove return removed entities',async()=>{const [,p]=await fresh(),s=createMultiListStore(p);await s.createList({id:'a',name:'A'});await s.addItem('a',{id:'i',text:'x'});assert.equal((await s.renameList('a','AA')).name,'AA');assert.deepEqual(await s.removeItem('a','i'),{id:'i',text:'x',done:false});assert.equal((await s.deleteList('a')).id,'a');assert.deepEqual(await s.snapshot(),{lists:[]});});
test('duplicates, invalid input, missing entities reject without mutation',async()=>{const [,p]=await fresh(),s=createMultiListStore(p);await s.createList({id:'a',name:'A'});await s.addItem('a',{id:'i',text:'x'});const before=await readFile(p,'utf8');for(const fn of [()=>s.createList({id:'a',name:'B'}),()=>s.createList({id:'b',name:' B '}),()=>s.addItem('a',{id:'i',text:'y'}),()=>s.addItem('a',{id:'j',text:' '}),()=>s.updateItem('a','i',{}),()=>s.updateItem('a','i',{done:'yes'}),()=>s.removeItem('a','z'),()=>s.renameList('z','Z')])await assert.rejects(fn());assert.equal(await readFile(p,'utf8'),before);});
test('corrupt/noncanonical state fails closed preserving bytes',async()=>{for(const raw of ['{bad',' {"lists":[]}','{"lists":[{"id":"a","name":"A","items":[],"x":1}]}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const s=createMultiListStore(p);await assert.rejects(s.snapshot(),/STATE_CORRUPT/);await assert.rejects(s.createList({id:'z',name:'Z'}),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('snapshot is a deep clone and persistence is compact canonical JSON',async()=>{const [,p]=await fresh(),s=createMultiListStore(p);await s.createList({id:'a',name:'A'});await s.addItem('a',{id:'i',text:'x'});const snap=await s.snapshot();snap.lists[0].items[0].text='mutated';assert.equal((await s.snapshot()).lists[0].items[0].text,'x');assert.equal(await readFile(p,'utf8'),JSON.stringify(await s.snapshot()));});
