import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createContactStore} from './contactStore.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-contact-'));return [d,join(d,'state','contacts.json')];}
test('missing is empty and read-only',async()=>{const [,p]=await fresh();const s=createContactStore(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add canonical contact and restart',async()=>{const [,p]=await fresh();const s=createContactStore(p);const c=await s.add({id:'c1',name:' Jeroen ',email:' Test@EXAMPLE.COM ',phone:' +32 123 ',tags:[' friend ','vip']});assert.deepEqual(c,{id:'c1',name:'Jeroen',email:'test@example.com',phone:'+32 123',tags:['friend','vip']});assert.deepEqual(await createContactStore(p).get('c1'),c);});
test('duplicate and invalid contact reject',async()=>{const [,p]=await fresh();const s=createContactStore(p);await s.add({id:'c',name:'C',email:'',phone:'',tags:[]});await assert.rejects(s.add({id:'c',name:'X',email:'',phone:'',tags:[]}),/DUPLICATE_ID/);for(const b of [{id:'',name:'A',email:'',phone:'',tags:[]},{id:'x',name:' ',email:'',phone:'',tags:[]},{id:'x',name:'A',email:1,phone:'',tags:[]},{id:'x',name:'A',email:'',phone:'',tags:['']},{id:'x',name:'A',email:'',phone:'',tags:[],extra:1}])await assert.rejects(s.add(b),/INVALID_CONTACT/);});
test('update canonicalizes and preserves order',async()=>{const [,p]=await fresh();const s=createContactStore(p);await s.add({id:'a',name:'A',email:'',phone:'',tags:[]});await s.add({id:'b',name:'B',email:'',phone:'',tags:[]});const c=await s.update('a',{email:' A@B.COM ',phone:' 123 ',tags:[' x ']});assert.deepEqual(c,{id:'a',name:'A',email:'a@b.com',phone:'123',tags:['x']});assert.deepEqual((await s.list()).map(x=>x.id),['a','b']);});
test('remove returns removed and missing mutations reject',async()=>{const [,p]=await fresh();const s=createContactStore(p);await s.add({id:'a',name:'A',email:'',phone:'',tags:[]});assert.deepEqual(await s.remove('a'),{id:'a',name:'A',email:'',phone:'',tags:[]});await assert.rejects(s.update('x',{name:'X'}),/NOT_FOUND/);await assert.rejects(s.remove('x'),/NOT_FOUND/);});
test('bad patch rejects',async()=>{const [,p]=await fresh();const s=createContactStore(p);await s.add({id:'a',name:'A',email:'',phone:'',tags:[]});for(const pch of [{},{id:'x'},{extra:1},{name:' '},{email:1},{tags:['']}])await assert.rejects(s.update('a',pch),/INVALID_PATCH/);});
test('corrupt state is preserved',async()=>{for(const body of ['{bad','{}','[{"id":"a","name":"A","email":"","phone":"","tags":[]},{"id":"a","name":"B","email":"","phone":"","tags":[]}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createContactStore(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.add({id:'z',name:'Z',email:'',phone:'',tags:[]}),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('deep clones and frozen API',async()=>{const [,p]=await fresh();const s=createContactStore(p);await s.add({id:'a',name:'A',email:'',phone:'',tags:['x']});const c=await s.get('a');c.tags.push('y');assert.deepEqual((await s.get('a')).tags,['x']);assert.equal(Object.isFrozen(s),true);});
