import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createBackupRestore} from './backupRestore.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-bak-'));return [d,join(d,'state','data.json'),join(d,'backup','data.bak.json')];}
test('missing state creates deterministic empty backup without creating state',async()=>{const [,s,b]=await fresh();const x=createBackupRestore(s);const env=await x.create(b);assert.equal(env.schema,'othrys.state.backup.v1');assert.deepEqual(env.state,{});assert.equal(await x.verify(b),true);await assert.rejects(access(s));});
test('backup canonicalizes and is deterministic',async()=>{const [d,s,b]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(s,'{"z":1,"a":{"y":2,"x":3}}');const x=createBackupRestore(s);await x.create(b);const once=await readFile(b,'utf8');await x.create(b);assert.equal(await readFile(b,'utf8'),once);assert.match(once,/"sha256":"[0-9a-f]{64}"/);assert.match(once,/"state":{"a":{"x":3,"y":2},"z":1}/);});
test('restore verifies and round-trips exact canonical state',async()=>{const [d,s,b]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(s,'{"b":2,"a":1}');const x=createBackupRestore(s);await x.create(b);await writeFile(s,'{"changed":true}');assert.deepEqual(await x.restore(b),{a:1,b:2});assert.equal(await readFile(s,'utf8'),'{"a":1,"b":2}');});
test('tampered backup rejects and leaves state unchanged',async()=>{const [d,s,b]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(s,'{"ok":1}');const x=createBackupRestore(s);await x.create(b);const env=JSON.parse(await readFile(b,'utf8'));env.state.ok=2;await writeFile(b,JSON.stringify(env));await assert.rejects(x.verify(b),/BACKUP_INVALID/);await assert.rejects(x.restore(b),/BACKUP_INVALID/);assert.equal(await readFile(s,'utf8'),'{"ok":1}');});
test('bad envelope shapes and unsafe keys reject',async()=>{const [d,s,b]=await fresh();await mkdir(join(d,'backup'),{recursive:true});const x=createBackupRestore(s);for(const body of ['{}','{"schema":"x","sha256":"0","state":{}}','{"schema":"othrys.state.backup.v1","sha256":"0","state":{"constructor":1}}']){await writeFile(b,body);await assert.rejects(x.verify(b),/BACKUP_INVALID/);}});
test('corrupt source state fails closed',async()=>{const [d,s,b]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(s,'{bad');const x=createBackupRestore(s);await assert.rejects(x.create(b),/STATE_CORRUPT/);await assert.rejects(access(b));});
test('API frozen',async()=>{const [,s]=await fresh();assert.equal(Object.isFrozen(createBackupRestore(s)),true);});
