import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createInventoryStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-inv-'));return [d,join(d,'state','inventory.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add canonical item persists and restart survives',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);const x=await s.add({id:'i1',name:' Widget ',quantity:2,unit:' pcs ',price:3.5});assert.deepEqual(x,{id:'i1',name:'Widget',quantity:2,unit:'pcs',price:3.5});assert.deepEqual(await createInventoryStore(p).get('i1'),x);});
test('duplicate and invalid items reject',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'i',name:'A',quantity:1,unit:'pc',price:1});await assert.rejects(s.add({id:'i',name:'B',quantity:1,unit:'pc',price:1}),/DUPLICATE_ID/);for(const x of [{id:'',name:'A',quantity:1,unit:'pc',price:1},{id:'x',name:' ',quantity:1,unit:'pc',price:1},{id:'x',name:'A',quantity:-1,unit:'pc',price:1},{id:'x',name:'A',quantity:1,unit:'',price:1},{id:'x',name:'A',quantity:1,unit:'pc',price:Infinity},{id:'x',name:'A',quantity:1,unit:'pc',price:1,extra:1}])await assert.rejects(s.add(x),/INVALID_ITEM/);});
test('update canonicalizes allowed fields and preserves order',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:1,unit:'pc',price:1});await s.add({id:'b',name:'B',quantity:2,unit:'pc',price:2});const x=await s.update('a',{name:' AA ',quantity:3,unit:' kg ',price:4});assert.deepEqual(x,{id:'a',name:'AA',quantity:3,unit:'kg',price:4});assert.deepEqual((await s.list()).map(x=>x.id),['a','b']);});
test('adjust persists positive and negative bounded deltas',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:5,unit:'pc',price:1});assert.equal((await s.adjust('a',2)).quantity,7);assert.equal((await s.adjust('a',-3)).quantity,4);assert.equal((await createInventoryStore(p).get('a')).quantity,4);});
test('adjust range and invalid delta fail closed',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:1,unit:'pc',price:1});await assert.rejects(s.adjust('a',-2),/RANGE/);for(const d of [0,NaN,Infinity,'1'])await assert.rejects(s.adjust('a',d));assert.equal((await s.get('a')).quantity,1);});
test('remove returns removed and missing mutations reject',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:1,unit:'pc',price:1});assert.deepEqual(await s.remove('a'),{id:'a',name:'A',quantity:1,unit:'pc',price:1});for(const f of [()=>s.update('x',{name:'X'}),()=>s.remove('x'),()=>s.adjust('x',1)])await assert.rejects(f(),/NOT_FOUND/);});
test('bad patch and corrupt state fail closed',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:1,unit:'pc',price:1});for(const q of [{},{id:'x'},{extra:1},{quantity:-1},{price:Infinity}])await assert.rejects(s.update('a',q),/INVALID_PATCH/);for(const body of ['{bad','{}','[{"id":"a","name":"A","quantity":1,"unit":"pc","price":1},{"id":"a","name":"B","quantity":2,"unit":"pc","price":2}]']){const [d,p2]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p2,body);const z=createInventoryStore(p2);await assert.rejects(z.list(),/STATE_CORRUPT/);await assert.rejects(z.add({id:'z',name:'Z',quantity:1,unit:'pc',price:1}),/STATE_CORRUPT/);assert.equal(await readFile(p2,'utf8'),body);}});
test('returned records are cloned and API frozen',async()=>{const [,p]=await fresh();const s=createInventoryStore(p);await s.add({id:'a',name:'A',quantity:1,unit:'pc',price:1});const x=await s.get('a');x.name='X';assert.equal((await s.get('a')).name,'A');assert.equal(Object.isFrozen(s),true);});

