import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createExpenseTracker} from './expenseTracker.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-exp-'));return [d,join(d,'state','expenses.json')];}
const e=(id='e1',amount=12.5,currency='EUR',category='food',date='2026-08-30',note=' lunch ')=>({id,amount,currency,category,date,note});
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);assert.deepEqual(await s.summary(),{count:0,totalByCurrency:{},totalByCategory:{}});await assert.rejects(access(p));});
test('add canonical expense persists and restart survives',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);const x=await s.add(e());assert.deepEqual(x,{...e(),note:'lunch'});assert.deepEqual(await createExpenseTracker(p).get('e1'),x);});
test('summary separates currencies and nests category totals',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);await s.add(e('a',10,'EUR','food'));await s.add(e('b',2,'USD','food'));await s.add(e('c',3,'EUR','books'));assert.deepEqual(await s.summary(),{count:3,totalByCurrency:{EUR:13,USD:2},totalByCategory:{books:{EUR:3},food:{EUR:10,USD:2}}});});
test('update canonicalizes and remove returns record',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);await s.add(e());assert.equal((await s.update('e1',{category:' travel ',note:' x '})).category,'travel');assert.equal((await s.remove('e1')).note,'x');await assert.rejects(s.remove('e1'),/NOT_FOUND/);});
test('validation rejects bad fields and patches before mutation',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);for(const bad of [e('',1),e('x',0),e('x',Infinity),e('x',1,'eur'),e('x',1,'EURO'),e('x',1,'EUR',' '),e('x',1,'EUR','x','2026-02-30'),{...e(),extra:1}]) await assert.rejects(s.add(bad),/INVALID_EXPENSE/);await s.add(e());for(const patch of [{},{id:'x'},{amount:0},{currency:'usd'},{date:'2026-02-30'},{extra:1}]) await assert.rejects(s.update('e1',patch),/INVALID_PATCH/);});
test('duplicate id rejects and state order remains stable',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);await s.add(e('a'));await s.add(e('b'));await assert.rejects(s.add(e('a')),/DUPLICATE_ID/);assert.deepEqual((await s.list()).map(x=>x.id),['a','b']);});
test('corrupt state fails closed and is preserved',async()=>{for(const body of ['{bad','{}','[{"id":"a","amount":1,"currency":"EUR","category":"x","date":"2026-01-01","note":""},{"id":"a","amount":1,"currency":"EUR","category":"x","date":"2026-01-01","note":""}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createExpenseTracker(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.add(e('z')),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('returned records are cloned and API frozen',async()=>{const [,p]=await fresh();const s=createExpenseTracker(p);await s.add(e());const x=await s.get('e1');x.category='mutated';assert.equal((await s.get('e1')).category,'food');assert.equal(Object.isFrozen(s),true);});
