import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createNotesStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-notes-'));return [d,join(d,'state','notes.json')];}
test('missing is empty and read-only',async()=>{const [,p]=await fresh();const s=createNotesStore(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add canonical note and restart',async()=>{const [,p]=await fresh();const s=createNotesStore(p);const n=await s.add({id:'n1',title:'  Title ',body:' body ',tags:[' a ','b']});assert.deepEqual(n,{id:'n1',title:'Title',body:'body',tags:['a','b']});assert.deepEqual(await createNotesStore(p).get('n1'),n);});
test('duplicate id rejects',async()=>{const [,p]=await fresh();const s=createNotesStore(p);await s.add({id:'n1',title:'a',body:'',tags:[]});await assert.rejects(s.add({id:'n1',title:'b',body:'',tags:[]}),/DUPLICATE_ID/);});
test('update supports title body tags and preserves order',async()=>{const [,p]=await fresh();const s=createNotesStore(p);await s.add({id:'a',title:'A',body:'',tags:[]});await s.add({id:'b',title:'B',body:'',tags:[]});await s.update('a',{body:' xx ',tags:['z']});assert.deepEqual(await s.list(),[{id:'a',title:'A',body:'xx',tags:['z']},{id:'b',title:'B',body:'',tags:[]}]);});
test('remove returns note and missing mutations reject',async()=>{const [,p]=await fresh();const s=createNotesStore(p);await s.add({id:'a',title:'A',body:'',tags:[]});assert.deepEqual(await s.remove('a'),{id:'a',title:'A',body:'',tags:[]});for(const f of [()=>s.update('x',{title:'x'}),()=>s.remove('x')]) await assert.rejects(f(),/NOT_FOUND/);});
test('validation rejects bad note and patch',async()=>{const [,p]=await fresh();const s=createNotesStore(p);for(const bad of [{id:'',title:'a',body:'',tags:[]},{id:'a',title:' ',body:'',tags:[]},{id:'a',title:'a',body:1,tags:[]},{id:'a',title:'a',body:'',tags:['']},{id:'a',title:'a',body:'',tags:[],extra:1}]) await assert.rejects(s.add(bad),/INVALID_NOTE/);await s.add({id:'a',title:'A',body:'',tags:[]});await assert.rejects(s.update('a',{}),/INVALID_PATCH/);await assert.rejects(s.update('a',{extra:1}),/INVALID_PATCH/);});
test('corrupt persisted state is preserved',async()=>{for(const body of ['{bad','{}','[{"id":"a","title":"A","body":"","tags":[]},{"id":"a","title":"B","body":"","tags":[]}]']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createNotesStore(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.add({id:'z',title:'Z',body:'',tags:[]}),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('returned notes deep clone tags and API frozen',async()=>{const [,p]=await fresh();const s=createNotesStore(p);await s.add({id:'a',title:'A',body:'',tags:['x']});const n=await s.get('a');n.tags.push('y');assert.deepEqual((await s.get('a')).tags,['x']);assert.equal(Object.isFrozen(s),true);});

