import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createCounterStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-counter-'));return [d,join(d,'state','counters.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createCounterStore(p);assert.equal(await s.get('x'),0);assert.deepEqual(await s.list(),{});await assert.rejects(access(p));});
test('increment decrement and set persist across restart',async()=>{const [,p]=await fresh();let s=createCounterStore(p);assert.equal(await s.increment('a'),1);assert.equal(await s.increment('a',2.5),3.5);assert.equal(await s.decrement('a',1.5),2);assert.equal(await s.set('b',5),5);s=createCounterStore(p);assert.deepEqual(await s.list(),{a:2,b:5});});
test('remove semantics and sorted list',async()=>{const [,p]=await fresh();const s=createCounterStore(p);await s.set('z',1);await s.set('a',2);assert.deepEqual(Object.keys(await s.list()),['a','z']);assert.equal(await s.remove('x'),false);assert.equal(await s.remove('a'),true);assert.deepEqual(await s.list(),{z:1});});
test('validation rejects bad names/deltas/values before mutation',async()=>{const [,p]=await fresh();const s=createCounterStore(p);for(const f of [()=>s.get(''),()=>s.increment('',1),()=>s.increment('a',Infinity),()=>s.decrement('a',NaN),()=>s.set('a',Infinity),()=>s.set('a','1')])await assert.rejects(f());await assert.rejects(access(p));});
test('overflow result rejects and preserves prior value',async()=>{const [,p]=await fresh();const s=createCounterStore(p);await s.set('a',Number.MAX_VALUE);await assert.rejects(s.increment('a',Number.MAX_VALUE),RangeError);assert.equal(await s.get('a'),Number.MAX_VALUE);});
test('corrupt state fails closed and is preserved',async()=>{for(const body of ['{bad','[]','{}','{"counters":{"a":null}}','{"counters":{"":1}}','{"counters":{"a":1},"extra":1}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createCounterStore(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.set('x',1),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('clear persists empty state and API frozen',async()=>{const [,p]=await fresh();const s=createCounterStore(p);await s.set('a',1);await s.clear();assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{counters:{}});assert.equal(Object.isFrozen(s),true);});
