import {promises as fs} from 'node:fs'; import {dirname} from 'node:path'; import {randomUUID} from 'node:crypto';
const bad=new Set(['__proto__','prototype','constructor']), clone=v=>structuredClone(v), plain=v=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
function canon(v){if(Array.isArray(v))return v.map(canon);if(v&&typeof v==='object'){if(!plain(v))throw 0;const o={};for(const k of Object.keys(v).sort()){if(bad.has(k))throw 0;o[k]=canon(v[k]);}return o;}if(typeof v==='undefined'||typeof v==='function'||typeof v==='symbol'||typeof v==='bigint'||(typeof v==='number'&&!Number.isFinite(v)))throw 0;return v;}
function envelope(v){if(!plain(v)||Object.keys(v).sort().join(',')!=='data,version'||!Number.isInteger(v.version)||v.version<1||!(Array.isArray(v.data)||plain(v.data)))throw new Error('STATE_CORRUPT');try{return{version:v.version,data:canon(v.data)}}catch{throw new Error('STATE_CORRUPT');}}
async function load(p,currentVersion){try{const e=envelope(JSON.parse(await fs.readFile(p,'utf8')));if(e.version>currentVersion)throw new Error('STATE_FUTURE_VERSION');return{missing:false,state:e};}catch(e){if(e?.code==='ENOENT')return{missing:true,state:{version:currentVersion,data:{}}};if(e?.message==='STATE_FUTURE_VERSION'||e?.message==='STATE_CORRUPT')throw e;throw new Error('STATE_CORRUPT');}}
async function persist(p,state){await fs.mkdir(dirname(p),{recursive:true});const t=`${p}.${process.pid}.${randomUUID()}.tmp`;try{await fs.writeFile(t,JSON.stringify(canon(state)),'utf8');await fs.rename(t,p);}catch(e){try{await fs.unlink(t);}catch{}throw e;}}
export function createStateMigrator(filePath,{currentVersion,migrations}={}){
 if(typeof filePath!=='string'||!filePath||!Number.isInteger(currentVersion)||currentVersion<1||!plain(migrations))throw new TypeError('config');
 async function inspect(){return clone((await load(filePath,currentVersion)).state);}
 async function migrate(){const loaded=await load(filePath,currentVersion),from=loaded.state.version;if(loaded.missing||from===currentVersion)return Object.freeze({fromVersion:currentVersion,toVersion:currentVersion,changed:false,state:clone(loaded.state)});let data=clone(loaded.state.data);for(let v=from;v<currentVersion;v++){const fn=migrations[v];if(typeof fn!=='function')throw new Error('MIGRATION_FAILED');try{data=canon(fn(clone(data)));if(!(Array.isArray(data)||plain(data)))throw 0;JSON.stringify(data);}catch{throw new Error('MIGRATION_FAILED');}}const state={version:currentVersion,data};await persist(filePath,state);return Object.freeze({fromVersion:from,toVersion:currentVersion,changed:true,state:clone(state)});}
 return Object.freeze({inspect,migrate});
}
