import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createUndoRedoStore} from './undoRedo.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-undo-'));return [d,join(d,'state','undo.json')];}
test('missing state is null and reads do not write',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p);assert.equal(await s.current(),null);assert.equal(await s.canUndo(),false);assert.equal(await s.canRedo(),false);await assert.rejects(access(p));});
test('commit persists canonical state and restart survives',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p);assert.deepEqual(await s.commit({z:1,a:{y:2,x:1}}),{a:{x:1,y:2},z:1});const raw=JSON.parse(await readFile(p,'utf8'));assert.deepEqual(raw,{current:{a:{x:1,y:2},z:1},past:[null],future:[]});assert.deepEqual(await createUndoRedoStore(p).current(),{a:{x:1,y:2},z:1});});
test('undo and redo persist exact transitions',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p);await s.commit(1);await s.commit(2);assert.equal(await s.undo(),1);assert.equal(await s.canRedo(),true);assert.equal(await s.redo(),2);assert.equal(await createUndoRedoStore(p).current(),2);});
test('new commit clears redo',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p);await s.commit('a');await s.commit('b');await s.undo();await s.commit('c');assert.equal(await s.canRedo(),false);assert.equal(await s.current(),'c');});test('history is bounded by limit',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p,{limit:2});await s.commit(1);await s.commit(2);await s.commit(3);assert.equal(await s.undo(),2);assert.equal(await s.undo(),1);assert.equal(await s.undo(),false);});
test('invalid limit and non-json state reject before write',async()=>{const [,p]=await fresh();for(const n of [0,101,1.5])assert.throws(()=>createUndoRedoStore(p,{limit:n}),RangeError);const s=createUndoRedoStore(p);for(const bad of [undefined,()=>{},Symbol('x'),1n,{x:Infinity}])await assert.rejects(s.commit(bad));await assert.rejects(access(p));});
test('corrupt persisted state fails closed and is preserved',async()=>{for(const raw of ['{bad','{}',JSON.stringify({current:1,past:[0,1,2],future:[]})]){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const s=createUndoRedoStore(p,{limit:2});await assert.rejects(s.current(),/STATE_CORRUPT/);await assert.rejects(s.commit(9),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('returned state is deep cloned and API frozen',async()=>{const [,p]=await fresh();const s=createUndoRedoStore(p);await s.commit({a:[1]});const x=await s.current();x.a.push(2);assert.deepEqual(await s.current(),{a:[1]});assert.equal(Object.isFrozen(s),true);});