import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createTagIndex} from './tagIndex.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-tags-'));return [d,join(d,'state','tags.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createTagIndex(p);assert.deepEqual(await s.listTags(),[]);assert.deepEqual(await s.get('x'),[]);await assert.rejects(access(p));});
test('set persists canonical tags and restart survives',async()=>{const [,p]=await fresh();let s=createTagIndex(p);await s.set('b',[' x ','y']);await s.set('a',['x']);assert.deepEqual(await s.get('x'),['a','b']);assert.deepEqual(await s.listTags(),['x','y']);s=createTagIndex(p);assert.deepEqual(await s.get('y'),['b']);});
test('set replaces prior tag membership',async()=>{const [,p]=await fresh();const s=createTagIndex(p);await s.set('a',['x','y']);await s.set('a',['z']);assert.deepEqual(await s.get('x'),[]);assert.deepEqual(await s.get('z'),['a']);});
test('invalid id tags and duplicate canonical tags reject before write',async()=>{const [,p]=await fresh();const s=createTagIndex(p);for(const args of [['', ['x']],['a','x'],['a',['']],['a',['x',' x ']]])await assert.rejects(s.set(...args));await assert.rejects(access(p));});
test('remove return value and clear persist',async()=>{const [,p]=await fresh();const s=createTagIndex(p);await s.set('a',['x']);assert.equal(await s.remove('z'),false);assert.equal(await s.remove('a'),true);assert.deepEqual(await s.get('x'),[]);await s.set('b',['y']);await s.clear();assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{records:{}});});
test('bad query tag rejects',async()=>{const [,p]=await fresh();const s=createTagIndex(p);for(const t of ['', '   ', 1])await assert.rejects(s.get(t));});
test('corrupt state fails closed and is preserved',async()=>{for(const body of ['{bad','[]','{}','{"records":{"a":["x"," x "]}}','{"records":{"":"x"}}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createTagIndex(p);await assert.rejects(s.listTags(),/STATE_CORRUPT/);await assert.rejects(s.set('z',['x']),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('API frozen',async()=>{const [,p]=await fresh();assert.equal(Object.isFrozen(createTagIndex(p)),true);});
