import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createHabitTracker} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-habit-'));return [d,join(d,'state','habits.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('add/check-in persist and derive streaks',async()=>{const [,p]=await fresh();let s=createHabitTracker(p);await s.add('h',' Walk ');for(const d of ['2026-01-01','2026-01-02','2026-01-04','2026-01-05','2026-01-06'])assert.equal(await s.checkIn('h',d),true);const v=await s.get('h');assert.deepEqual(v,{id:'h',name:'Walk',dates:['2026-01-01','2026-01-02','2026-01-04','2026-01-05','2026-01-06'],currentStreak:3,longestStreak:3});s=createHabitTracker(p);assert.deepEqual(await s.get('h'),v);});
test('duplicate check-in is idempotent and uncheck semantics work',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);await s.add('h','H');assert.equal(await s.checkIn('h','2026-02-01'),true);const before=await readFile(p,'utf8');assert.equal(await s.checkIn('h','2026-02-01'),false);assert.equal(await readFile(p,'utf8'),before);assert.equal(await s.uncheck('h','2026-02-02'),false);assert.equal(await s.uncheck('h','2026-02-01'),true);});
test('strict dates reject impossible calendar dates',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);await s.add('h','H');for(const d of ['2026-02-30','2026-13-01','26-01-01','2026-1-01'])await assert.rejects(s.checkIn('h',d));});
test('missing habit mutations and remove semantics',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);await assert.rejects(s.checkIn('x','2026-01-01'),/NOT_FOUND/);await assert.rejects(s.uncheck('x','2026-01-01'),/NOT_FOUND/);assert.equal(await s.remove('x'),false);await s.add('h','H');assert.equal(await s.remove('h'),true);assert.equal(await s.get('h'),undefined);});
test('duplicate id and invalid habit reject before write',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);for(const [id,n] of [['','x'],['a',' '],[1,'x']])await assert.rejects(s.add(id,n));await s.add('a','A');await assert.rejects(s.add('a','B'),/DUPLICATE_ID/);});
test('corrupt state fails closed and is preserved',async()=>{for(const body of ['{bad','[]','{}','{"habits":[{"id":"a","name":"A","dates":["2026-01-01","2026-01-01"]}]}','{"habits":[{"id":"a","name":" A ","dates":[]}]}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createHabitTracker(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.add('z','Z'),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('returned state is cloned and API frozen',async()=>{const [,p]=await fresh();const s=createHabitTracker(p);await s.add('a','A');await s.checkIn('a','2026-01-01');const v=await s.get('a');v.dates.push('2026-01-02');assert.deepEqual((await s.get('a')).dates,['2026-01-01']);assert.equal(Object.isFrozen(s),true);});
