import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createSettingsStore} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-settings-'));return [d,join(d,'state','settings.json')];}
const defaults={theme:'dark',pageSize:20,compact:false,tags:[]};
test('defaults resolve without writing',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);assert.deepEqual(await s.all(),defaults);assert.equal(await s.get('theme'),'dark');await assert.rejects(access(p));});
test('set persists override and survives restart',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);await s.set('theme','light');assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{theme:'light'});assert.equal(await createSettingsStore(p,defaults).get('theme'),'light');});
test('resolved all merges overrides over defaults',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);await s.set('pageSize',50);assert.deepEqual(await s.all(),{theme:'dark',pageSize:50,compact:false,tags:[]});});
test('unknown key and type mismatch reject before write',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);await assert.rejects(s.set('missing',1),/UNKNOWN_SETTING/);await assert.rejects(s.set('pageSize','50'),/SETTING_TYPE/);await assert.rejects(access(p));});
test('reset key removes only override; resetAll removes all',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);await s.set('theme','light');await s.set('compact',true);await s.reset('theme');assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{compact:true});assert.equal(await s.get('theme'),'dark');await s.resetAll();assert.deepEqual(JSON.parse(await readFile(p,'utf8')),{});});
test('corrupt override file fails closed and is preserved',async()=>{const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,'{bad');const s=createSettingsStore(p,defaults);await assert.rejects(s.all(),/STATE_CORRUPT/);await assert.rejects(s.set('theme','light'),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),'{bad');});
test('override file cannot contain unknown keys or wrong types',async()=>{for(const body of ['{"extra":1}','{"pageSize":"x"}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);await assert.rejects(createSettingsStore(p,defaults).all(),/STATE_CORRUPT/);}});
test('array values are cloned so callers cannot mutate stored/default state',async()=>{const [,p]=await fresh();const s=createSettingsStore(p,defaults);const a=await s.get('tags');a.push('x');assert.deepEqual(await s.get('tags'),[]);await s.set('tags',['a']);const b=await s.get('tags');b.push('b');assert.deepEqual(await s.get('tags'),['a']);});
test('API is frozen and defaults are not mutated',async()=>{const [,p]=await fresh();const copy=JSON.stringify(defaults);const s=createSettingsStore(p,defaults);assert.equal(Object.isFrozen(s),true);await s.set('theme','light');assert.equal(JSON.stringify(defaults),copy);});

