import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createTimeTracker} from './timeTracker.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-time-'));return [d,join(d,'state','time.json')];}
test('missing is empty and reads do not write',async()=>{const [,p]=await fresh();const s=createTimeTracker(p);assert.deepEqual(await s.list(),[]);assert.equal(await s.get('x'),undefined);await assert.rejects(access(p));});
test('start/stop persist and derive exact duration',async()=>{const [,p]=await fresh();let s=createTimeTracker(p);const a='2026-01-01T10:00:00.000Z',b='2026-01-01T10:30:00.000Z';assert.deepEqual(await s.start('e',' Work ',a),{id:'e',label:'Work',startedAt:a,stoppedAt:null,durationMs:null});assert.deepEqual(await s.stop('e',b),{id:'e',label:'Work',startedAt:a,stoppedAt:b,durationMs:1800000});s=createTimeTracker(p);assert.equal((await s.get('e')).durationMs,1800000);});
test('duplicate, missing and already-stopped transitions reject',async()=>{const [,p]=await fresh();const s=createTimeTracker(p);const a='2026-01-01T10:00:00.000Z',b='2026-01-01T10:01:00.000Z';await s.start('e','E',a);await assert.rejects(s.start('e','E',a),/DUPLICATE_ID/);await assert.rejects(s.stop('x',b),/NOT_FOUND/);await s.stop('e',b);await assert.rejects(s.stop('e','2026-01-01T10:02:00.000Z'),/ALREADY_STOPPED/);});
test('timestamps must be canonical and stop strictly later',async()=>{const [,p]=await fresh();const s=createTimeTracker(p);for(const t of ['2026-01-01','2026-01-01T10:00:00Z','bad'])await assert.rejects(s.start('x','X',t),/INVALID_TIME/);await s.start('e','E','2026-01-01T10:00:00.000Z');for(const t of ['2026-01-01T09:59:59.999Z','2026-01-01T10:00:00.000Z'])await assert.rejects(s.stop('e',t),/INVALID_TIME/);});
test('remove semantics and deep cloned views',async()=>{const [,p]=await fresh();const s=createTimeTracker(p);assert.equal(await s.remove('x'),false);await s.start('e','E','2026-01-01T10:00:00.000Z');const v=await s.get('e');v.label='mutated';assert.equal((await s.get('e')).label,'E');assert.equal(await s.remove('e'),true);assert.equal(await s.get('e'),undefined);});
test('input validation rejects before write',async()=>{const [,p]=await fresh();const s=createTimeTracker(p);for(const a of [['','E','2026-01-01T10:00:00.000Z'],['e',' ','2026-01-01T10:00:00.000Z'],[1,'E','2026-01-01T10:00:00.000Z']])await assert.rejects(s.start(...a));await assert.rejects(access(p));});
test('corrupt state fails closed and is preserved',async()=>{for(const body of ['{bad','[]','{}','{"entries":[{"id":"a","label":"A","startedAt":"2026-01-01T10:00:00.000Z","stoppedAt":null},{"id":"a","label":"B","startedAt":"2026-01-01T11:00:00.000Z","stoppedAt":null}]}','{"entries":[{"id":"a","label":" A ","startedAt":"2026-01-01T10:00:00.000Z","stoppedAt":null}]}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createTimeTracker(p);await assert.rejects(s.list(),/STATE_CORRUPT/);await assert.rejects(s.start('z','Z','2026-01-01T12:00:00.000Z'),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('API frozen',async()=>{const [,p]=await fresh();assert.equal(Object.isFrozen(createTimeTracker(p)),true);});
