import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,access} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createDeskTool} from './deskTool.mjs';
async function fresh(){return mkdtemp(join(tmpdir(),'othrys-l224-'));}
test('composed factory is frozen exact API and missing reads do not write',async()=>{const d=await fresh(),x=createDeskTool(d);assert(Object.isFrozen(x));assert.deepEqual(Object.keys(x).sort(),['addTodo','exportJson','getSettings','importJson','listTodos','removeTodo','setSetting','summary','updateTodo']);assert.deepEqual(await x.getSettings(),{theme:'dark',compact:false});assert.deepEqual(await x.listTodos(),[]);assert.deepEqual(await x.summary(),{todoCount:0,doneCount:0,openCount:0,completionPct:0});await assert.rejects(access(join(d,'settings.json')));await assert.rejects(access(join(d,'todos.json')));});
test('settings and todo CRUD delegate and summary is deterministic',async()=>{const d=await fresh(),x=createDeskTool(d);assert.equal((await x.setSetting('compact',true)).compact,true);await x.addTodo({id:'a',text:'one',done:false});await x.addTodo({id:'b',text:'two',done:true});await x.updateTodo('a',{done:true});assert.deepEqual(await x.summary(),{todoCount:2,doneCount:2,openCount:0,completionPct:100});assert.equal((await x.removeTodo('b')).id,'b');assert.equal((await x.summary()).completionPct,100);});
test('export is canonical composed snapshot and restart survives',async()=>{const d=await fresh(),x=createDeskTool(d);await x.setSetting('theme','light');await x.addTodo({id:'a',text:'one'});const out=await x.exportJson();assert.equal(out,JSON.stringify({settings:{theme:'light',compact:false},todos:[{id:'a',text:'one',done:false}]}));assert.equal(await createDeskTool(d).exportJson(),out);});
test('valid import stages through composed stores then replaces live state',async()=>{const d=await fresh(),x=createDeskTool(d);await x.setSetting('theme','light');await x.addTodo({id:'old',text:'old'});const target=JSON.stringify({settings:{theme:'dark',compact:true},todos:[{id:'n',text:'new',done:true}]});assert.deepEqual(await x.importJson(target),{settings:{theme:'dark',compact:true},todos:[{id:'n',text:'new',done:true}]});assert.equal(await x.exportJson(),target);});
test('invalid import leaves both live files byte-identical',async()=>{const d=await fresh(),x=createDeskTool(d);await x.setSetting('theme','light');await x.addTodo({id:'a',text:'one'});const sp=join(d,'settings.json'),tp=join(d,'todos.json'),sb=await readFile(sp,'utf8'),tb=await readFile(tp,'utf8');for(const bad of ['{bad',JSON.stringify({settings:{theme:'dark'},todos:[]}),JSON.stringify({settings:{theme:'dark',compact:false},todos:[{id:'a',text:' ',done:false}]})]){await assert.rejects(x.importJson(bad),/INVALID_IMPORT/);assert.equal(await readFile(sp,'utf8'),sb);assert.equal(await readFile(tp,'utf8'),tb);}});
test('composed delegates preserve their validation',async()=>{const d=await fresh(),x=createDeskTool(d);await assert.rejects(x.setSetting('unknown',1),/UNKNOWN_SETTING/);await assert.rejects(x.addTodo({id:'a',text:' '}),/INVALID_TODO/);await x.addTodo({id:'a',text:'ok'});await assert.rejects(x.addTodo({id:'a',text:'dup'}),/DUPLICATE_ID/);});
