import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path';
import {createActivityLog} from './activityLog.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l221-'));return [d,join(d,'state','activity.json')];}
const e=(id,type='NOTE',data={x:1})=>({id,type,data});
test('missing list empty, no write, frozen exact API',async()=>{const [,p]=await fresh(),a=createActivityLog(p);assert(Object.isFrozen(a));assert.deepEqual(Object.keys(a).sort(),['append','list']);assert.deepEqual(await a.list(),[]);await assert.rejects(access(p));});
test('append persists canonical exact schema and survives restart',async()=>{const [,p]=await fresh(),a=createActivityLog(p);assert.deepEqual(await a.append(e('a')),{seq:1,...e('a')});assert.equal(await readFile(p,'utf8'),JSON.stringify({events:[{seq:1,...e('a')}] }));assert.deepEqual(await createActivityLog(p).list(),[{seq:1,...e('a')}]);});
test('bounded feed keeps newest while sequence stays monotonic',async()=>{const [,p]=await fresh(),a=createActivityLog(p,{limit:2});await a.append(e('a'));await a.append(e('b'));await a.append(e('c'));assert.deepEqual((await a.list()).map(x=>[x.seq,x.id]),[[2,'b'],[3,'c']]);const r=await a.append(e('d'));assert.equal(r.seq,4);});
test('duplicate and invalid events reject without mutation',async()=>{const [,p]=await fresh(),a=createActivityLog(p);await a.append(e('a'));const before=await readFile(p,'utf8');for(const bad of [e('a'),e(' ','X',{}),e('b',' ',{}),e('b','X',{n:Infinity})])await assert.rejects(a.append(bad));const cyc={};cyc.self=cyc;await assert.rejects(a.append(e('b','X',cyc)));assert.equal(await readFile(p,'utf8'),before);});
test('corrupt/noncanonical state fails closed preserving bytes',async()=>{for(const raw of ['{bad',' {"events":[]} ',JSON.stringify({events:[{seq:1,...e('a')},{seq:1,...e('b')} ]})]){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const a=createActivityLog(p);await assert.rejects(a.list(),/STATE_CORRUPT/);await assert.rejects(a.append(e('z')),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('list returns deep clones and limit validates',async()=>{const [,p]=await fresh(),a=createActivityLog(p);await a.append(e('a','X',{arr:[1]}));const x=await a.list();x[0].data.arr.push(2);assert.deepEqual((await a.list())[0].data.arr,[1]);for(const n of [0,10001,1.5])assert.throws(()=>createActivityLog(p,{limit:n}),/INVALID_LIMIT/);});
