import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createPreferenceProfile} from '../src/index.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l222-'));return [d,join(d,'state','prefs.json')];}
test('missing get returns defaults, no write, frozen API',async()=>{const [,p]=await fresh(),s=createPreferenceProfile(p,{defaults:{theme:'dark',nested:{x:1}}});assert(Object.isFrozen(s));assert.deepEqual(Object.keys(s).sort(),['get','patch','replace','reset']);assert.deepEqual(await s.get(),{nested:{x:1},theme:'dark'});await assert.rejects(access(p));});
test('patch deep merges, arrays replace, canonical persist and restart',async()=>{const [,p]=await fresh(),s=createPreferenceProfile(p,{defaults:{a:{x:1,y:2},arr:[1],z:true}});assert.deepEqual(await s.patch({a:{y:3},arr:[2]}),{a:{x:1,y:3},arr:[2],z:true});assert.equal(await readFile(p,'utf8'),'{"a":{"x":1,"y":3},"arr":[2],"z":true}');assert.deepEqual(await createPreferenceProfile(p,{defaults:{}}).get(),{a:{x:1,y:3},arr:[2],z:true});});
test('replace and reset reload disk',async()=>{const [,p]=await fresh(),s=createPreferenceProfile(p,{defaults:{a:1}});await s.replace({b:2});await writeFile(p,'{"c":3}');assert.deepEqual(await s.get(),{c:3});assert.deepEqual(await s.reset(),{a:1});});
test('invalid input rejects before mutation',async()=>{const [,p]=await fresh(),s=createPreferenceProfile(p);await s.replace({a:1});const before=await readFile(p,'utf8');for(const bad of [[],{a:Infinity},{a:undefined}])await assert.rejects(s.patch(bad),/INVALID_PROFILE/);const cyc={};cyc.self=cyc;await assert.rejects(s.replace(cyc),/INVALID_PROFILE/);assert.equal(await readFile(p,'utf8'),before);});
test('corrupt and noncanonical state fail closed preserving bytes',async()=>{for(const raw of ['{bad',' {"a":1}','{"b":2,"a":1}']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,raw);const s=createPreferenceProfile(p);await assert.rejects(s.get(),/STATE_CORRUPT/);await assert.rejects(s.patch({x:1}),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),raw);}});
test('outputs are deep clones',async()=>{const [,p]=await fresh(),s=createPreferenceProfile(p);const out=await s.replace({a:[1]});out.a.push(2);assert.deepEqual((await s.get()).a,[1]);});

