import test from 'node:test'; import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,access,mkdir} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join} from 'node:path'; import {createStateTransfer} from './stateTransfer.mjs';
async function fresh(){const d=await mkdtemp(join(tmpdir(),'othrys-l2-xfer-'));return [d,join(d,'state','data.json')];}
test('missing exports empty object without writing',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);assert.equal(await s.exportJson(),'{}');assert.deepEqual(await s.read(),{});await assert.rejects(access(p));});
test('import canonicalizes recursively and persists deterministic JSON',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);const v=await s.importJson('{"z":1,"a":{"y":2,"x":3},"arr":[{"b":2,"a":1}]}');assert.deepEqual(v,{a:{x:3,y:2},arr:[{a:1,b:2}],z:1});assert.equal(await readFile(p,'utf8'),'{"a":{"x":3,"y":2},"arr":[{"a":1,"b":2}],"z":1}');assert.equal(await s.exportJson(),await readFile(p,'utf8'));});
test('arrays preserve order while object keys sort',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);await s.importJson('[{"z":1,"a":2},3,2,1]');assert.equal(await s.exportJson(),'[{"a":2,"z":1},3,2,1]');});
test('invalid import leaves prior disk unchanged',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);await s.importJson('{"ok":1}');for(const bad of ['{bad','42','null','"x"']) await assert.rejects(s.importJson(bad),/INVALID_IMPORT/);assert.equal(await readFile(p,'utf8'),'{"ok":1}');});
test('unsafe keys are rejected anywhere',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);for(const bad of ['{"__proto__":{}}','{"a":{"constructor":1}}','[{"prototype":1}]']) await assert.rejects(s.importJson(bad),/INVALID_IMPORT/);await assert.rejects(access(p));});
test('corrupt persisted state fails closed and is preserved',async()=>{for(const body of ['{bad','42']){const [d,p]=await fresh();await mkdir(join(d,'state'),{recursive:true});await writeFile(p,body);const s=createStateTransfer(p);await assert.rejects(s.read(),/STATE_CORRUPT/);await assert.rejects(s.exportJson(),/STATE_CORRUPT/);assert.equal(await readFile(p,'utf8'),body);}});
test('read returns deep clone and API is frozen',async()=>{const [,p]=await fresh();const s=createStateTransfer(p);await s.importJson('{"a":{"b":1}}');const x=await s.read();x.a.b=9;assert.equal((await s.read()).a.b,1);assert.equal(Object.isFrozen(s),true);});
